Repository liquality/wallet, pull requests merged in 2021-12, with the labels that each got.

#416 fix: Update terra swap gas limit
  src/swaps/liquality/LiqualitySwapProvider.js
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#419 fix: typo in test rpcUrl for sovryn
  src/build.config.js
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#425 feat: Update near packages to 1.11.0
  package-lock.json
  package.json
Labels: size/S, 🔍 Ready for Review, 🌟 Needs more Approvals

#421 refactor: update wallet creation screen order
  src/App.vue
  src/assets/icons/new_wallet_text.svg
  src/assets/icons/wallet_tagline.svg
  src/router/index.js
  src/views/Onboarding/OnboardingHome.vue
  src/views/Onboarding/OnboardingPassword.vue
  src/views/Onboarding/OnboardingSetup.vue
  src/views/Splash.vue
  tests/Pages/HomePage.js
  tests/e2e/02_import_wallet.spec.js
  tests/e2e/03_receive.spec.js
  tests/e2e/04_send.spec.js
  tests/e2e/05_swap.spec.js
  tests/e2e/07_add_custom_token.spec.js
  tests/e2e/08_custom_fee.spec.js
  tests/e2e/09_menu_options.spec.js
  tests/e2e/11_oneinch_dapp_injection.spec.js
  tests/e2e/12_remove_custom_token.spec.js
  tests/e2e/13_manage_accounts.spec.js
  tests/e2e/14_liquality_booster.spec.js
  tests/e2e/15_1inch_swap_provider.spec.js
  tests/e2e/16_uniswap_provider.spec.js
  tests/e2e/17_uniswap_dapp_injection.spec.js
  tests/e2e/18_sushi_dapp_injection.spec.js
  tests/e2e/19_private_keys_export.spec.js
  tests/e2e/rsk_tests/06_derived_path.spec.js
  tests/e2e/rsk_tests/10_fastbtc_swap.spec.js
  tests/e2e/rsk_tests/13_rsk_bridge_injection.spec.js
  tests/e2e/rsk_tests/14_swap_sovryn_amm.spec.js
  tests/e2e/swap_tests/01_rbtc_btc_swap.spec.js
  tests/e2e/terra_tests/19_terra_send.spec.js
  tests/e2e/terra_tests/20_terra_swaps.spec.js
  tests/e2e/terra_tests/21_terra_anchor_dapp.spec.js
  tests/e2e/terra_tests/22_terra_mirror_finance_dapp.spec.js
Labels: size/XL, 🔍 Ready for Review, 🌟 Needs more Approvals

#427 fix: liq 716 ledger to regular swap
  package-lock.json
  package.json
  src/assets/scss/_overrides.scss
  src/components/Head.vue
  src/store/actions/getUnusedAddresses.js
  src/store/actions/hardware-wallet/getLedgerAccounts.js
  src/store/actions/initializeAddresses.js
  src/store/actions/updateBalances.js
  src/store/actions/updateTransactionFee.js
  src/store/factory/client.js
  src/store/getters.js
  src/store/index.js
  src/store/modules/app/actions.js
  src/store/modules/app/mutations.js
  src/store/modules/app/state.js
  src/store/mutations.js
  src/swaps/SwapProvider.js
  src/swaps/views/Timeline.vue
  src/utils/accounts.js
  src/utils/coinFormatter.js
  src/utils/ledger-bridge-provider/BitcoinLedgerBridgeApp.js
  src/utils/ledger-bridge-provider/BitcoinLedgerBridgeProvider.js
  src/utils/ledger-bridge-provider/EthereumLedgerBridgeApp.js
  src/utils/ledger-bridge-provider/utils.js
  src/views/Accounts/HardwareWallet/HardwareWallet.vue
  src/views/Accounts/HardwareWallet/Unlock.vue
  src/views/Details/SwapDetails.vue
  src/views/Details/TransactionDetails.vue
Labels: size/XXL, ✅ Approved

#429 feat: PR discord webhook
  .github/workflows/pullrequests.yml
  .github/workflows/release.yml
Labels: size/S, 🔍 Ready for Review, 🌟 Needs more Approvals

#420 feat: Added Terra custom token add
  README.md
  tests/e2e/07_add_custom_token.spec.js
  tests/e2e/12_remove_custom_token.spec.js
  tests/e2e/terra_tests/20_terra_swaps.spec.js
  tests/e2e/terra_tests/23_terra_custom_token.spec.js
Labels: size/L, 🔍 Ready for Review

#430 fix: add terra chain icon
  src/assets/icons/assets/terra_chain.svg
  src/utils/accounts.js
Labels: size/S, 🔍 Ready for Review

#422 feat: Improve UX for initial loading of overview page
  src/components/WalletAccounts.vue
  src/store/mutations.js
  src/views/Wallet/Wallet.vue
  src/views/Wallet/WalletStats.vue
  tests/Pages/OverviewPage.js
  tests/Pages/SeedWordsPage.js
  tests/Pages/SwapPage.js
  tests/e2e/rsk_tests/06_derived_path.spec.js
  tests/e2e/swap_tests/01_rbtc_btc_swap.spec.js
  tests/e2e/terra_tests/20_terra_swaps.spec.js
Labels: size/L, 🔍 Ready for Review

#468 fix: wallet build fixed
  package-lock.json
  package.json
  tests/Pages/HomePage.js
  tests/Pages/OverviewPage.js
  tests/Pages/PasswordPage.js
  tests/Pages/ReceivePage.js
  tests/Pages/SearchAssetPage.js
  tests/Pages/SeedWordsPage.js
  tests/Pages/SendPage.js
  tests/Pages/SwapPage.js
  tests/Pages/TransactionDetailsPage.js
  tests/e2e/05_swap.spec.js
  tests/e2e/07_add_custom_token.spec.js
  tests/e2e/09_menu_options.spec.js
  tests/e2e/11_oneinch_dapp_injection.spec.js
  tests/e2e/12_remove_custom_token.spec.js
  tests/e2e/14_liquality_booster.spec.js
  tests/e2e/16_uniswap_provider.spec.js
  tests/e2e/rsk_tests/10_fastbtc_swap.spec.js
  tests/e2e/swap_tests/01_rbtc_btc_swap.spec.js
  tests/e2e/terra_tests/23_terra_custom_token.spec.js
Labels: size/L, 🔍 Ready for Review

#470 fix: Terra SEND test issue
  .mocharc.yml
  package-lock.json
  package.json
  tests/e2e/02_import_wallet.spec.js
  tests/e2e/03_receive.spec.js
  tests/e2e/04_send.spec.js
  tests/e2e/05_swap.spec.js
  tests/e2e/07_add_custom_token.spec.js
  tests/e2e/08_custom_fee.spec.js
  tests/e2e/09_menu_options.spec.js
  tests/e2e/11_oneinch_dapp_injection.spec.js
  tests/e2e/12_remove_custom_token.spec.js
  tests/e2e/13_manage_accounts.spec.js
  tests/e2e/14_liquality_booster.spec.js
  tests/e2e/15_1inch_swap_provider.spec.js
  tests/e2e/16_uniswap_provider.spec.js
  tests/e2e/17_uniswap_dapp_injection.spec.js
  tests/e2e/18_sushi_dapp_injection.spec.js
  tests/e2e/19_private_keys_export.spec.js
  tests/e2e/rsk_tests/06_derived_path.spec.js
  tests/e2e/rsk_tests/10_fastbtc_swap.spec.js
  tests/e2e/rsk_tests/13_rsk_bridge_injection.spec.js
  tests/e2e/rsk_tests/14_swap_sovryn_amm.spec.js
  tests/e2e/swap_tests/01_rbtc_btc_swap.spec.js
  tests/e2e/terra_tests/19_terra_send.spec.js
  tests/e2e/terra_tests/20_terra_swaps.spec.js
  tests/e2e/terra_tests/21_terra_anchor_dapp.spec.js
  tests/e2e/terra_tests/22_terra_mirror_finance_dapp.spec.js
  tests/e2e/terra_tests/23_terra_custom_token.spec.js
  tests/pages/HomePage.js
  tests/pages/OverviewPage.js
  tests/pages/PasswordPage.js
  tests/pages/ReceivePage.js
  tests/pages/SearchAssetPage.js
  tests/pages/SeedWordsPage.js
  tests/pages/SendPage.js
  tests/pages/SwapPage.js
  tests/pages/TransactionDetailsPage.js
Labels: size/L, 🔍 Ready for Review

#477 feat: LIQ-865 custom token added
  tests/e2e/07_add_custom_token.spec.js
  tests/e2e/terra_tests/23_terra_custom_token.spec.js
  tests/pages/AddCustomTokenPage.js
Labels: size/XL, 🔍 Ready for Review

#479 feat: LIQ-866, remove custom token test
  tests/e2e/07_add_custom_token.spec.js
  tests/e2e/12_remove_custom_token.spec.js
  tests/pages/AddCustomTokenPage.js
  tests/pages/OverviewPage.js
Labels: size/L, 🔍 Ready for Review

#418 feat: liq 671 liquality boost via sovryn
  src/build.config.js
  src/swaps/liqualityboost/LiqualityBoostSwapProvider.js
Labels: 🔍 Ready for Review, size/M

#378 fix: min value for liqualityboost and minimum default swap value
  src/views/Swap/Swap.vue
Labels: size/S, 🔍 Ready for Review, 🌟 Needs more Approvals

#465 fix: Matic swap error + silent errors
  package-lock.json
  package.json
  src/store/actions/performNextAction/index.js
  src/store/actions/performNextAction/utils.js
Labels: 🔍 Ready for Review, size/M

#414 refactor: LIQ-704
  src/utils/address.js
  src/views/Account.vue
  src/views/Receive.vue
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#451 refactor: GAP Analysis
  src/views/ImportWallet.vue
  src/views/Onboarding/OnboardingHome.vue
  src/views/Onboarding/OnboardingPassword.vue
  src/views/Onboarding/OnboardingSetup.vue
  src/views/Splash.vue
  src/views/UnlockWallet.vue
Labels: 🔍 Ready for Review, size/M

#492 feat: Terra LUNA export private key tests
  package-lock.json
  package.json
  src/manifest.json
  tests/e2e/03_receive.spec.js
  tests/e2e/04_send.spec.js
  tests/e2e/05_swap.spec.js
  tests/e2e/08_custom_fee.spec.js
  tests/e2e/14_liquality_booster.spec.js
  tests/e2e/15_1inch_swap_provider.spec.js
  tests/e2e/16_uniswap_provider.spec.js
  tests/e2e/19_private_keys_export.spec.js
  tests/e2e/rsk_tests/10_fastbtc_swap.spec.js
  tests/e2e/rsk_tests/14_swap_sovryn_amm.spec.js
  tests/e2e/swap_tests/01_rbtc_btc_swap.spec.js
  tests/e2e/terra_tests/19_terra_send.spec.js
  tests/e2e/terra_tests/20_terra_swaps.spec.js
  tests/pages/OverviewPage.js
Labels: 🔍 Ready for Review, size/M

#474 fix: custom tokens improvements
  src/store/utils.js
  src/swaps/uniswap/UniswapSwapProvider.js
  src/views/CustomToken.vue
Labels: size/XS, 🔍 Ready for Review

#496 fix: polygonscan correct url for mumbai testnet
  src/utils/asset.js
Labels: size/XS, 🔍 Ready for Review

#497 fix: do not show rates when they are missing
  src/components/TransactionList.vue
  src/utils/coinFormatter.js
  src/views/Swap/ReceiveInput.vue
  src/views/Swap/Swap.vue
Labels: 🔍 Ready for Review, size/M

#489 feat: do not allow swap in boost if user cannot cover fee
  src/views/Swap/Swap.vue
Labels: size/XS, 🔍 Ready for Review

#498 feat: Create wallet tests fixed
  .github/CODEOWNERS
  .github/workflows/pullrequests.yml
  tests/e2e/03_receive.spec.js
  tests/e2e/rsk_tests/06_derived_path.spec.js
  tests/e2e/rsk_tests/14_swap_sovryn_amm.spec.js
  tests/pages/PasswordPage.js
  tests/pages/SeedWordsPage.js
Labels: 🔍 Ready for Review, size/M

#471 fix: Feature legder flow messages screens
  package-lock.json
  src/assets/scss/style.scss
  src/background.js
  src/components/LedgerSignRequestModal.vue
  src/components/OperationErrorModal.vue
  src/store/actions/executeRequest.js
  src/store/actions/getUnusedAddresses.js
  src/store/actions/hardware-wallet/getLedgerAccounts.js
  src/store/actions/initializeAddresses.js
  src/store/actions/updateAccountBalance.js
  src/store/actions/updateBalances.js
  src/store/factory/client.js
  src/store/getters.js
  src/store/modules/app/actions.js
  src/swaps/fastbtc/FastbtcSwapProvider.js
  src/utils/accounts.js
  src/utils/ledger-bridge-provider/BitcoinLedgerBridgeApp.js
  src/utils/ledger-bridge-provider/BitcoinLedgerBridgeProvider.js
  src/utils/ledger-bridge-provider/config.js
  src/utils/ledger-bridge-provider/utils.js
  src/views/Accounts/HardwareWallet/HardwareWallet.vue
  src/views/Accounts/HardwareWallet/Unlock.vue
  src/views/Details/SwapDetails.vue
  src/views/Send/Send.vue
  src/views/Swap/Swap.vue
Labels: size/XL, 🔍 Ready for Review

#508 feat: cryptoassets 1.7.2
  package-lock.json
  package.json
Labels: size/XS, ✅ Approved

#509 chore: cryptoassets to 1.7.2
  package-lock.json
  package.json
Labels: size/XS, ✅ Approved

#510 test: LIQ-851
  .github/workflows/build-test-mainnet.yml
  .github/workflows/build-test-testnet.yml
  .github/workflows/pullrequests.yml
  package-lock.json
  package.json
  src/manifest.json
  test/e2e/rsk_tests/rsk_sovryn_amm.spec.js
  test/pages/OverviewPage.js
Labels: 🔍 Ready for Review, size/M

#515 fix: overrides the near node url for mainnet
  src/store/factory/client.js
  test/e2e/rsk_tests/06_derived_path.spec.js
Labels: size/XS, 🔍 Ready for Review

#520 fix: overrides near rpc url
  src/store/factory/client.js
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals
