Repository liquality/wallet, pull requests merged in 2022-10, with the labels that each got.

#880 Ext 48 apply and cancel button not working on
  src/components/FeeSelector.vue
  src/components/NavBar.vue
  src/views/Details/NFTTransactionDetails.vue
  src/views/PermissionSend.vue
Labels: size/S, ✅ Approved

#874 feat: easy evm integrations
  README.md
  package.json
  src/components/CustomFees.vue
  src/views/CustomToken.vue
  src/views/Receive.vue
  yarn.lock
Labels: size/L, 🔍 Ready for Review

#886 chore: updated latest translation files
  src/locales/cb/common.json
  src/locales/cb/terms.html
  src/locales/es/common.json
  src/locales/es/components.json
  src/locales/es/pages.json
  src/locales/es/terms.html
  src/locales/ph/common.json
  src/locales/ph/terms.html
  src/locales/pt/common.json
  src/locales/pt/components.json
  src/locales/pt/pages.json
  src/locales/pt/terms.html
  src/locales/zh/common.json
  src/locales/zh/pages.json
  src/locales/zh/terms.html
Labels: size/XXL, 🔍 Ready for Review

#882 Ext 58 cancel button doesnt work on warning
  src/views/Onboarding/SeedPhrase/Warning.vue
Labels: 🔍 Ready for Review, size/M

#892 Labels should appear in their native language
  src/locales/en/common.json
Labels: size/S, 🔍 Ready for Review

#872 fix: added some fixes to prop binding and and nft screens
  src/components/NFT/NFTAsset.vue
  src/components/NFT/NFTAssets.vue
  src/views/Accounts/Create.vue
  src/views/Details/NFTAssetDetails.vue
  src/views/Details/NFTTransactionDetails.vue
  src/views/Send/SendNFT.vue
  src/views/Wallet/WalletNFTs.vue
  src/views/Wallet/WalletTabs.vue
  yarn.lock
Labels: size/L, ✅ Approved

#879 fix: fixed ledger to ledger send for custom fees and blank screen error
  src/views/Details/SwapDetails.vue
  src/views/Send/Send.vue
Labels: size/S, 🔍 Ready for Review

#893 fix: added back terms.html for all languages
  src/locales/cb/terms.html
  src/locales/es/terms.html
  src/locales/ph/terms.html
  src/locales/pt/terms.html
  src/locales/zh/terms.html
Labels: size/XXL, 🔍 Ready for Review

#894 fix: added missing translation keys
  src/locales/es/common.json
  src/locales/ph/common.json
  src/locales/pt/common.json
  src/locales/zh/common.json
Labels: size/XS, 🔍 Ready for Review

#895 fix: override should only happen when enabled
  src/contentScript.js
Labels: size/S, 🔍 Ready for Review

#896 fix: injection should still work if not overriding
  src/contentScript.js
Labels: size/XS, 🔍 Ready for Review

#897 fix: assets must be fetched from store instead of cryptoassets
  package.json
  src/broker/Background.js
  src/store/modules/app/executeRequest.js
  src/swaps/views/Timeline.vue
  src/transactions/views/Timeline.vue
  src/views/Details/NFTTransactionDetails.vue
  src/views/Details/TransactionDetails.vue
  src/views/PermissionSignPsbt.vue
  src/views/Receive.vue
  yarn.lock
Labels: size/XL, 🔍 Ready for Review

#898 Fix/ext 152
  src/broker/Background.js
Labels: size/XS, ✅ Approved

#899 LIFI + Debridge + Move to Goerli
  package.json
  src/assets/icons/swapProviders/debridge.svg
  src/assets/icons/swapProviders/lifi.svg
  src/views/Swap/Swap.vue
  yarn.lock
Labels: size/XL, ✅ Approved

#900 Fixes Linear EXT-112
  src/locales/en/pages.json
Labels: size/XS, ✅ Approved

#903 chore: 76.0 into master
  .env
  .github/workflows/release.yml
  package.json
  src/assets/icons/swapProviders/debridge.svg
  src/assets/icons/swapProviders/lifi.svg
  src/broker/Background.js
  src/components/AccountTooltip.vue
  src/components/CustomFees.vue
  src/components/CustomFeesEIP1559.vue
  src/components/FeeSelector.vue
  src/components/NFT/NFTAsset.vue
  src/components/NFT/NFTAssets.vue
  src/components/NavBar.vue
  src/components/WhatsNewModal.vue
  src/contentScript.js
  src/locales/cb/common.json
  src/locales/en/common.json
  src/locales/en/pages.json
  src/locales/es/common.json
  src/locales/es/components.json
  src/locales/es/pages.json
  src/locales/pt/common.json
  src/locales/pt/components.json
  src/locales/pt/pages.json
  src/locales/zh/common.json
  src/locales/zh/pages.json
  src/manifest.json
  src/store/modules/app/executeRequest.js
  src/swaps/views/Timeline.vue
  src/transactions/views/Timeline.vue
  src/views/Accounts/Create.vue
  src/views/CustomToken.vue
  src/views/Details/NFTAssetDetails.vue
  src/views/Details/NFTTransactionDetails.vue
  src/views/Details/SwapDetails.vue
  src/views/Details/TransactionDetails.vue
  src/views/Experiments.vue
  src/views/Onboarding/SeedPhrase/PhraseReveal.vue
  src/views/Onboarding/SeedPhrase/Warning.vue
  src/views/PermissionSend.vue
  src/views/PermissionSignPsbt.vue
  src/views/Receive.vue
  src/views/Send/Send.vue
  src/views/Send/SendNFT.vue
  src/views/Swap/Swap.vue
  src/views/Wallet/WalletNFTs.vue
  src/views/Wallet/WalletTabs.vue
  test/e2e/menu_options.spec.js
  test/unit/solana.test.js
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#887 Ext 35 whats new facelift
  .env
  package.json
  src/assets/icons/arrow_left.svg
  src/assets/icons/arrow_right.svg
  src/assets/scss/_overrides.scss
  src/assets/scss/style.scss
  src/assets/whats_new.json
  src/assets/whats_new_sample.json
  src/components/Modal.vue
  src/components/NFT/NFTAsset.vue
  src/components/WhatsNewModal.vue
  src/components/icons/Clap.vue
  src/components/icons/Logo.vue
  src/components/icons/NFTQuantity.vue
  src/components/icons/Star.vue
  src/locales/cb/whats_new.json
  src/locales/en/whats_new.json
  src/locales/es/whats_new.json
  src/locales/ph/whats_new.json
  src/locales/pt/whats_new.json
  src/locales/zh/whats_new.json
  src/main.js
  src/views/Details/NFTAssetDetails.vue
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#905 feat: Open customer questionnaire after user has deinstalled the chro…
  src/background.js
Labels: size/XS, 🔍 Ready for Review

#906 Ext 35 whats new facelift
  package.json
  src/assets/scss/style.scss
  src/components/ActivityFilter.vue
  src/components/AnalyticsOptInModal.vue
  src/components/CopyAddress.vue
  src/components/CustomFees.vue
  src/components/CustomFeesEIP1559.vue
  src/components/DetailsContainer.vue
  src/components/LedgerRequestMessage.vue
  src/components/NFT/NFTAssets.vue
  src/components/NFT/NFTTimeline.vue
  src/components/WhatsNewModal.vue
  src/main.js
  src/swaps/views/Timeline.vue
  src/transactions/views/Timeline.vue
  src/views/Accounts/Create.vue
  src/views/Accounts/ExportPrivateKey.vue
  src/views/AssetList.vue
  src/views/Details/NFTTransactionDetails.vue
  src/views/Details/SwapDetails.vue
  src/views/Details/TransactionDetails.vue
  src/views/Onboarding/ImportWallet.vue
  src/views/Onboarding/OnboardingHome.vue
  src/views/Onboarding/OnboardingPassword.vue
  src/views/Onboarding/OnboardingSetup.vue
  src/views/Onboarding/SeedPhrase/PhraseReveal.vue
  src/views/PermissionSend.vue
  src/views/PermissionSign.vue
  src/views/Receive.vue
  src/views/Send/Send.vue
  src/views/Send/SendNFT.vue
  src/views/Swap/QuotesModal.vue
  src/views/Swap/ReceiveInput.vue
  src/views/Swap/SendInput.vue
  src/views/Swap/Swap.vue
  src/views/Wallet/Wallet.vue
  src/views/Wallet/WalletNFTs.vue
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#908 test: fix uniswap test
  .github/workflows/pullrequests.yml
  test/e2e/dapp_injection_tests/avalanche_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/dapp_injection.spec.js
  test/e2e/dapp_injection_tests/oneinch_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/rsk_sovryn_injection.spec.js
  test/e2e/dapp_injection_tests/rsk_sovryn_injection_create_wallet.spec.js
  test/e2e/dapp_injection_tests/sushi_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/terra_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/uniswap_dapp_injection.spec.js
  test/e2e/enable_disable_assets.spec.js
  test/e2e/hop_tests/hop_swaps.spec.js
  test/e2e/service_provider_tests/uniswap_provider.spec.js
Labels: size/XXL, 🔍 Ready for Review

#910 fix: what's new modal
  src/App.vue
  src/components/WhatsNewModal.vue
  src/store/modules/app/actions.js
  src/store/modules/app/mutations.js
  src/store/modules/app/state.js
Labels: size/L, ✅ Approved

#909 ci: upgrade github actions
  .github/workflows/pullrequests.yml
  test/e2e/dapp_injection_tests/dapp_injection.spec.js
Labels: size/S, 🔍 Ready for Review
