Repository liquality/wallet, pull requests merged in 2022-12, with the labels that each got.

#944 Assets count fix
  src/views/Swap/Swap.vue
  src/views/Wallet/WalletStats.vue
Labels: size/S, ✅ Approved

#943 Add new string to other languages
  src/locales/cb/common.json
  src/locales/es/common.json
  src/locales/ph/common.json
  src/locales/pt/common.json
  src/locales/zh/common.json
Labels: size/S, ✅ Approved

#940 fix: review validation to can send flag inside Send View
  .env
  src/components/CopyError.vue
  src/components/EthRequiredMessage.vue
  src/components/Head.vue
  src/components/OperationErrorModal.vue
  src/locales/cb/common.json
  src/locales/cb/components.json
  src/locales/cb/pages.json
  src/locales/en/common.json
  src/locales/en/components.json
  src/locales/en/pages.json
  src/locales/es/common.json
  src/locales/es/components.json
  src/locales/es/pages.json
  src/locales/ph/common.json
  src/locales/ph/components.json
  src/locales/ph/pages.json
  src/locales/pt/common.json
  src/locales/pt/components.json
  src/locales/pt/pages.json
  src/locales/zh/common.json
  src/locales/zh/components.json
  src/locales/zh/pages.json
  src/swaps/views/Timeline.vue
  src/views/Account.vue
  src/views/Experiments.vue
  src/views/Send/Send.vue
  src/views/Send/SendNFT.vue
  src/views/Swap/Swap.vue
Labels: size/L, 🔍 Ready for Review

#946 chore: set metamask emulated = true by default
  src/pageProvider/ethereumProvider.js
Labels: size/XS, 🔍 Ready for Review

#952 Activity filter fix
  src/components/Head.vue
  src/views/Account.vue
Labels: size/XS

#953 Ext 234 only show self accounts tokens and non
  package.json
  src/App.vue
  src/assets/scss/style.scss
  src/background.js
  src/components/Head.vue
  src/components/WhatsNewModal.vue
  src/main.js
  src/router/index.js
  src/store/modules/app/actions.js
  src/store/modules/app/mutations.js
  src/views/Splash.vue
  src/views/Swap/Accounts.vue
  src/views/Swap/Swap.vue
  src/views/Wallet/Wallet.vue
  src/views/Wallet/WalletActivity.vue
  src/views/Wallet/WalletTabs.vue
  yarn.lock
Labels: size/XL, 🔍 Ready for Review

#954 Fix/terms condition modal onboarding lazy loading views
  src/assets/scss/style.scss
  src/views/Onboarding/OnboardingPassword.vue
Labels: size/XS, 🔍 Ready for Review

#956 fix: update error report config once state loads
  .env
  package.json
  src/broker/index.js
  yarn.lock
Labels: 🔍 Ready for Review, size/M

#957 Fix/loading balance and preload screens
  package.json
  src/App.vue
  src/main.js
  src/manifest.json
  src/router/index.js
  src/views/Wallet/Wallet.vue
Labels: size/L, 🔍 Ready for Review

#958 Ext 238 | Ethereum nft IPFS image fix
  src/views/Details/NFTAssetDetails.vue
Labels: size/XS, ✅ Approved

#959 Error message display fix
  src/swaps/views/Timeline.vue
Labels: size/XS, ✅ Approved

#960 Set minimum amount that can be sent and prevent dust transactions
  src/locales/en/common.json
  src/views/Send/Send.vue
  src/views/Send/SendInput.vue
Labels: ✅ Approved, size/M

#961 Refactor Minimum Send amount alert to use warning alert
  src/locales/en/common.json
  src/views/Send/Send.vue
  src/views/Send/SendInput.vue
Labels: size/S, ✅ Approved

#962 fix: modified login to validate min send amount for solana and btc
  package.json
  src/main.js
  src/manifest.json
  src/views/Send/Send.vue
Labels: 🔍 Ready for Review, size/M

#963 fix: fixed commented required gas message
  src/views/Send/Send.vue
Labels: size/S, 🔍 Ready for Review

#964 Translations for Minimum send amount is
  src/locales/cb/common.json
  src/locales/en/common.json
  src/locales/es/common.json
  src/locales/ph/common.json
  src/locales/pt/common.json
  src/locales/zh/common.json
Labels: size/S, 🔍 Ready for Review, ✅ Approved

#955 Settings page and routes refactor
  .gitignore
  package.json
  src/background.js
  src/components/CustomRpcSettingsForm.vue
  src/components/NavBar.vue
  src/locales/cb/common.json
  src/locales/en/common.json
  src/locales/en/pages.json
  src/locales/es/common.json
  src/locales/ph/common.json
  src/locales/pt/common.json
  src/locales/zh/common.json
  src/main.js
  src/manifest.json
  src/router/index.js
  src/views/Experiments.vue
  src/views/NetworkSettings.vue
  src/views/SettingItems.vue
  src/views/Settings.vue
  src/views/SettingsFooter.vue
  vue.config.js
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#966 Set minimum balance for rent exemption
  src/locales/cb/common.json
  src/locales/cb/components.json
  src/locales/cb/pages.json
  src/locales/cb/terms.html
  src/locales/cb/whats_new.json
  src/locales/en/common.json
  src/locales/es/common.json
  src/locales/es/components.json
  src/locales/es/pages.json
  src/locales/es/terms.html
  src/locales/es/whats_new.json
  src/locales/ph/common.json
  src/locales/ph/components.json
  src/locales/ph/pages.json
  src/locales/ph/terms.html
  src/locales/ph/whats_new.json
  src/locales/pt/common.json
  src/locales/pt/components.json
  src/locales/pt/pages.json
  src/locales/pt/terms.html
  src/locales/pt/whats_new.json
  src/locales/zh/common.json
  src/locales/zh/components.json
  src/locales/zh/pages.json
  src/locales/zh/terms.html
  src/locales/zh/whats_new.json
  src/views/Send/AssetAvailableAmount.vue
  src/views/Send/Send.vue
  src/views/Send/SendInput.vue
Labels: size/XXL, ✅ Approved

#967 fix: updated locale files / terms and conditions
  package.json
  src/locales/cb/terms.html
  src/locales/es/terms.html
  src/locales/ph/terms.html
  src/locales/pt/terms.html
  src/locales/zh/terms.html
  src/manifest.json
Labels: size/XXL, 🔍 Ready for Review

#969 Change the word Cadenas to Redes in Spanish
  src/locales/es/pages.json
Labels: size/XS, ✅ Approved

#968 IPFS image url fix
  src/views/Details/NFTAssetDetails.vue
Labels: size/XS, ✅ Approved
