Repository liquality/wallet, pull requests merged in 2022-01, with the labels that each got.

#512 fix: allow boost swaps only if the user has enough bridge asset amoun…
  src/views/Swap/Swap.vue
Labels: size/XS, 🔍 Ready for Review

#535 fix: fix some failed tests & 0.52.2 release
  package-lock.json
  package.json
  src/manifest.json
  src/views/Wallet/WalletStats.vue
  test/e2e/02_import_wallet.spec.js
  test/e2e/swap_tests/01_rbtc_btc_swap.spec.js
  test/e2e/terra_tests/20_terra_swaps.spec.js
  test/pages/OverviewPage.js
Labels: size/L, 🔍 Ready for Review

#392 feat: migrate 1inch to v4
  src/build.config.js
  src/store/factory/swapProvider.js
  src/store/getters.js
  src/swaps/liqualityboost/LiqualityBoostSwapProvider.js
  src/swaps/oneinch/OneinchSwapProvider.js
  src/utils/asset.js
  src/utils/swaps.js
Labels: 🔍 Ready for Review, size/M

#548 Revert "feat: migrate 1inch to v4"
  src/build.config.js
  src/store/factory/swapProvider.js
  src/store/getters.js
  src/swaps/liqualityboost/LiqualityBoostSwapProvider.js
  src/swaps/oneinch/OneinchSwapProvider.js
  src/utils/asset.js
  src/utils/swaps.js
Labels: 🔍 Ready for Review, size/M

#547 Revert "feat: Update indexer endpoints to new chainhub infra"
  src/build.config.js
  src/store/factory/client.js
Labels: size/S, 🔍 Ready for Review

#554 core: master merge
  package-lock.json
  package.json
  src/components/WatsNewModal.vue
  src/manifest.json
Labels: size/S, 🔍 Ready for Review

#555 Revert "Revert "feat: Update indexer endpoints to new chainhub infra""
  src/build.config.js
  src/store/factory/client.js
Labels: size/S, 🔍 Ready for Review

#556 Revert "Revert "feat: migrate 1inch to v4""
  src/build.config.js
  src/store/factory/swapProvider.js
  src/store/getters.js
  src/swaps/liqualityboost/LiqualityBoostSwapProvider.js
  src/swaps/oneinch/OneinchSwapProvider.js
  src/utils/asset.js
  src/utils/swaps.js
Labels: size/M

#552 fix: Do not allow negative fees
  src/components/CustomFees.vue
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#389 feat: Support for failed state in send transaction
  src/assets/icons/failed.svg
  src/broker/notification.js
  src/components/TransactionStatus.vue
  src/store/actions/performNextAction/send.js
  src/utils/history.js
  src/views/Details/TransactionDetails.vue
Labels: 🔍 Ready for Review, size/M

#399 feat: EIP1559 Custom fee
  package-lock.json
  package.json
  src/assets/scss/_overrides.scss
  src/components/CustomFeesEIP1559.vue
  src/store/factory/client.js
  src/utils/ledger-bridge-provider/EthereumLedgerBridgeProvider.js
  src/views/Account.vue
  src/views/Details/TransactionDetails.vue
  src/views/Send/Send.vue
  src/views/Swap/Swap.vue
  test/e2e/swap_tests/01_rbtc_btc_swap.spec.js
  test/e2e/terra_tests/20_terra_swaps.spec.js
Labels: size/XL, 🔍 Ready for Review

#558 refactor: LIQ-871
  src/views/Receive.vue
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#569 feat: Update CAL packages to 1.12.0
  package-lock.json
  package.json
Labels: 🔍 Ready for Review, size/M

#488 feat: add send timeline
  src/broker/notification.js
  src/components/TransactionStatus.vue
  src/store/actions/executeRequest.js
  src/store/actions/newSwap.js
  src/store/actions/sendTransaction.js
  src/swaps/views/Timeline.vue
  src/transactions/views/Timeline.vue
  src/views/Account.vue
  src/views/Details/TransactionDetails.vue
  src/views/PermissionSend.vue
  src/views/Receive.vue
  src/views/Send/Send.vue
Labels: size/XL, 🔍 Ready for Review

#557 feat: injection management
  src/assets/icons/connection_connected.svg
  src/assets/icons/connection_disconnected.svg
  src/broker/Background.js
  src/components/ChainDropdown.vue
  src/components/ConnectionDrawer.vue
  src/components/Head.vue
  src/contentScript.js
  src/inject.js
  src/manifest.json
  src/store/actions/addExternalConnection.js
  src/store/actions/index.js
  src/store/actions/requestOriginAccess.js
  src/store/actions/toggleInjection.js
  src/store/mutations.js
  src/store/state.js
  src/views/Settings.vue
Labels: size/L, 🔍 Ready for Review

#493 fix: resolve migration issue
  src/store/migrations/index.js
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#391 feat: correct refund icon in swap details
  src/views/Details/SwapDetails.vue
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#519 feat: rework send.vue and swap.vue to both match new design
  src/assets/icons/arrow-down.svg
  src/components/AccountTooltip.vue
  src/components/DetailsContainer.vue
  src/components/Head.vue
  src/components/NavBar.vue
  src/views/Send/Send.vue
  src/views/Send/SendInput.vue
  src/views/Swap/ReceiveInput.vue
  src/views/Swap/SendInput.vue
  src/views/Swap/Swap.vue
Labels: size/L, 🔍 Ready for Review

#385 fix: thorchain swap
  src/build.config.js
  src/swaps/thorchain/ThorchainSwapProvider.js
  src/swaps/views/Timeline.vue
  src/views/Account.vue
  src/views/Details/SwapDetails.vue
  src/views/Swap/Swap.vue
Labels: size/L, 🔍 Ready for Review

#524 feat: Add fuse network
  src/assets/icons/assets/fuse.svg
  src/build.config.js
  src/components/CustomFees.vue
  src/store/factory/client.js
  src/store/getters.js
  src/utils/accounts.js
  src/utils/asset.js
  src/utils/derivationPath.js
  src/utils/fees.js
  src/utils/networks.js
  src/views/CustomToken.vue
  src/views/Receive.vue
Labels: size/L, 🔍 Ready for Review

#426 feat: improving terra usdt swaps
  package-lock.json
  src/store/factory/client.js
  src/swaps/liquality/LiqualitySwapProvider.js
  src/utils/asset.js
Labels: size/S, 🔍 Ready for Review

#574 refactor: update wallet screens - onboarding
  src/views/Onboarding/OnboardingPassword.vue
  src/views/UnlockWallet.vue
  test/e2e/rsk_tests/06_derived_path.spec.js
Labels: size/XS, ✅ Approved

#576 feat: check failed transactions on timeline diagram
  src/swaps/views/Timeline.vue
Labels: size/S, ✅ Approved

#578 test: refactor dapp tests
  src/components/ConnectionDrawer.vue
  src/components/Head.vue
  test/e2e/09_menu_options.spec.js
  test/e2e/14_liquality_booster.spec.js
  test/e2e/17_uniswap_dapp_injection.spec.js
  test/e2e/18_sushi_dapp_injection.spec.js
  test/e2e/19_private_keys_export.spec.js
  test/e2e/rsk_tests/10_fastbtc_swap.spec.js
Labels: size/L, 🔍 Ready for Review

#580 fix: Injection management + lint
  src/components/ConnectionDrawer.vue
  src/components/Head.vue
  src/store/factory/client.js
  src/utils/asset.js
  src/utils/networks.js
  src/views/CustomToken.vue
Labels: 🔍 Ready for Review, size/M

#406 fix: export private key followup
  src/views/Accounts/ExportPrivateKey.vue
Labels: size/S, 🔍 Ready for Review

#579 fix: Add watcher for max fee
  src/components/CustomFeesEIP1559.vue
Labels: 🔍 Ready for Review, 🌟 Needs more Approvals, size/M

#575 feat: Enable eip1559 for matic mainnet
  src/views/Send/Send.vue
  src/views/Swap/Swap.vue
Labels: size/S, 🔍 Ready for Review

#582 fix: read assets from local cache and also cryptoassets package
  src/store/getters.js
  src/utils/cryptoassets.js
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#584 fix: typo related to merging many branches in dev - resolved
  src/views/Swap/Swap.vue
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#585 fix: double dollar sign ui bug
  src/views/Swap/Swap.vue
Labels: size/XS, ✅ Approved

#581 fix: Speed up ui changes
  src/views/Details/SwapDetails.vue
  src/views/Details/TransactionDetails.vue
Labels: ✅ Approved, size/M

#586 test: added some test utils to get the addresses from home screen
  test/e2e/03_receive.spec.js
  test/e2e/08_custom_fee.spec.js
  test/e2e/rsk_tests/06_derived_path.spec.js
  test/e2e/rsk_tests/13_rsk_bridge_injection.spec.js
  test/e2e/swap_tests/01_rbtc_btc_swap.spec.js
  test/e2e/terra_tests/19_terra_send.spec.js
  test/pages/OverviewPage.js
  test/utils/TestUtils.js
Labels: 🔍 Ready for Review

#599 test: refactor derivation paths tests
  package-lock.json
  test/e2e/11_oneinch_dapp_injection.spec.js
  test/e2e/rsk_tests/06_derived_path.spec.js
  test/pages/SeedWordsPage.js
Labels: 🔍 Ready for Review, size/M

#605 fix: 1inch test to validate fiat values
  test/e2e/05_swap.spec.js
  test/e2e/15_1inch_swap_provider.spec.js
  test/e2e/swap_tests/01_rbtc_btc_swap.spec.js
  test/pages/SwapPage.js
Labels: size/L, 🔍 Ready for Review

#606 fix: UI issues from QA report
  src/components/CustomFeesEIP1559.vue
  src/views/Swap/Swap.vue
Labels: size/S, 🔍 Ready for Review, 🌟 Needs more Approvals

#432 fix: replace toNumber with toString to prevent exponent
  src/store/actions/updateAccountBalance.js
  src/store/actions/updateBalances.js
  src/views/Send/Send.vue
Labels: size/S, 🔍 Ready for Review

#607 test: LIQ-990
  package-lock.json
  package.json
  test/e2e/15_1inch_swap_provider.spec.js
  test/pages/OverviewPage.js
  test/pages/PasswordPage.js
  test/pages/SwapPage.js
Labels: size/L, 🔍 Ready for Review

#609 Fix total fiat balance
  src/store/actions/updateAccountBalance.js
  src/store/actions/updateBalances.js
  src/store/getters.js
  src/views/Details/SwapDetails.vue
Labels: 🔍 Ready for Review, 🌟 Needs more Approvals, size/M

#610 Fix/liq 940 display high fees when actually fees are low
  src/views/Swap/Swap.vue
Labels: size/XS, ✅ Approved

#587 feat: Add eip1559 to be displayed when user is setting fee for dapp i…
  src/components/CustomFeesEIP1559.vue
  src/views/PermissionSend.vue
Labels: 🔍 Ready for Review, 🌟 Needs more Approvals, size/M

#611 fix: fix-liq-989-swap-to-rsk-NaN-custom-fee
  src/views/Swap/Swap.vue
Labels: size/XS, ✅ Approved

#608 fix: connection management
  src/App.vue
  src/broker/Background.js
  src/broker/Script.js
  src/components/Head.vue
Labels: 🔍 Ready for Review, ✅ Approved, 🌟 Needs more Approvals, size/M

#612 fix: because of eip integration some timeline diagram were missing a …
  src/views/Details/SwapDetails.vue
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#614 fix: wallet flow
  src/views/Onboarding/OnboardingSetup.vue
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#613 feat: Add 2 new tabs for eip1559 transactions
  src/components/CustomFeesEIP1559.vue
Labels: size/L, ✅ Approved

#617 refactor: Remove ununsed event labels
  package-lock.json
  package.json
  src/background.js
  src/manifest.json
  src/views/PermissionSend.vue
  src/views/Swap/Swap.vue
Labels: 🔍 Ready for Review, 🌟 Needs more Approvals, size/M

#615 fix: fix routes
  src/views/ImportWallet.vue
  src/views/Onboarding/OnboardingHome.vue
  src/views/Onboarding/OnboardingPassword.vue
  src/views/Onboarding/OnboardingSetup.vue
  src/views/Splash.vue
Labels: size/S, 🔍 Ready for Review

#618 test: LIQ-641 tests added
  test/e2e/13_manage_accounts.spec.js
Labels: size/S, 🔍 Ready for Review

#620 fix: Label for a total fee
  src/components/CustomFeesEIP1559.vue
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#622 feat: Update CAL packages to 1.13.1 terra packages were updated
  package-lock.json
  package.json
Labels: 🔍 Ready for Review, 🌟 Needs more Approvals, size/M

#624 fix: Use 1559 fee provider for polygon mainnet
  src/store/factory/client.js
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#619 refactor: password validation
  src/views/Onboarding/OnboardingPassword.vue
Labels: size/S, 🔍 Ready for Review, 🌟 Needs more Approvals

#627 fix: refactor SWAP & SWAP status change events
  src/background.js
Labels: 🔍 Ready for Review, 🌟 Needs more Approvals, size/M

#626 feat: show receive fee
  src/views/Details/SwapDetails.vue
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#631 fix: updated hw web bridge package
  package-lock.json
  package.json
  src/background.js
  src/store/factory/client.js
  src/views/Enable.vue
  test/e2e/08_custom_fee.spec.js
Labels: size/S, 🔍 Ready for Review

#639 test: LIQ-945
  src/transactions/views/Timeline.vue
  src/views/Details/TransactionDetails.vue
  test/e2e/04_send.spec.js
  test/e2e/16_uniswap_provider.spec.js
Labels: 🔍 Ready for Review, size/M

#630 fix: Save selected asset when custom fee is selected in order to open…
  src/views/Swap/Swap.vue
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#640 feat: Update CAL packages to 1.13.3
  package-lock.json
  package.json
Labels: 🔍 Ready for Review, size/M
