Repository liquality/wallet, pull requests merged in 2022-11, with the labels that each got.

#901 fix: support liquality errors
  .env
  package.json
  src/broker/Background.js
  src/broker/Foreground.js
  src/components/CustomFeesEIP1559.vue
  src/pageProvider/bitcoinProvider.js
  src/pageProvider/ethereumProvider.js
  src/pageProvider/globalEthereumProvider.js
  src/pageProvider/nearProvider.js
  src/pageProvider/pageProvider.js
  src/pageProvider/solanaProvider.js
  src/pageProvider/terraProvider.js
  src/store/modules/app/handlePaymentUri.js
  src/store/modules/app/replyPermission.js
  src/store/modules/app/requestOriginAccess.js
  src/store/modules/app/requestPermission.js
  src/store/modules/app/requestUnlockWallet.js
  src/swaps/views/Timeline.vue
  src/utils/hardware-wallet.js
  src/utils/localization.js
  src/views/Accounts/HardwareWallet/HardwareWallet.vue
  src/views/CustomToken.vue
  src/views/Onboarding/SeedPhrase/LoginPhrase.vue
  src/views/PermissionSend.vue
  src/views/PermissionSign.vue
  src/views/PermissionTerra.vue
  src/views/Send/Send.vue
  src/views/Send/SendNFT.vue
  src/views/Swap/Swap.vue
  src/views/UnlockWallet.vue
  src/views/Wallet/NFTStats.vue
  src/views/Wallet/Wallet.vue
  yarn.lock
Labels: size/XL, 🔍 Ready for Review

#913 feat: Self-Custodial Multi-Chain Wallet that is 100% Open Source INF-38
  src/manifest.json
Labels: size/XS, 🔍 Ready for Review

#920 fix: nft collection item not opening correctly
  package.json
  src/components/NFT/NFTAsset.vue
  src/views/Details/NFTAssetDetails.vue
  yarn.lock
Labels: size/XL, ✅ Approved

#911 fix: show number of NFTs
  src/locales/en/pages.json
  src/views/Wallet/NFTStats.vue
  src/views/Wallet/WalletTabs.vue
Labels: size/L, ✅ Approved

#917 Remove liquality atomic swaps
  src/views/Swap/SwapProvidersInfoModal.vue
Labels: size/S, 🔍 Ready for Review

#912 Updated defaultAmount to max
  src/views/Swap/Swap.vue
Labels: size/XS, 🔍 Ready for Review

#923 Fix cor 57 send transaction response from injection
  src/pageProvider/ethereumProvider.js
Labels: size/XS, ✅ Approved

#922 Updating locale files from crowdin
  src/locales/cb/common.json
  src/locales/cb/components.json
  src/locales/cb/pages.json
  src/locales/es/common.json
  src/locales/es/components.json
  src/locales/es/pages.json
  src/locales/ph/common.json
  src/locales/ph/components.json
  src/locales/ph/pages.json
  src/locales/pt/common.json
  src/locales/pt/pages.json
  src/locales/zh/common.json
  src/locales/zh/pages.json
Labels: size/XXL, 🔍 Ready for Review

#924 Fixing small check for NFTs
  src/components/WalletAccounts.vue
  src/views/Swap/Swap.vue
  src/views/Swap/SwapProvidersInfoModal.vue
Labels: size/S, ✅ Approved

#926 Enable decimal field customisation on pulling data from external token
  src/views/CustomToken.vue
Labels: size/XS, ✅ Approved

#928 fix SOL NFTs not showing
  src/views/Details/NFTAssetDetails.vue
Labels: size/XS, 🔍 Ready for Review

#927 LIQ-179 | Added user notification for existing custom tokens
  src/locales/en/pages.json
  src/views/CustomToken.vue
Labels: size/S, 🔍 Ready for Review

#925 feat: implemented chrome store multilang support
  package.json
  src/locales/cb/desc.md
  src/locales/cb/messages.json
  src/locales/en/desc.md
  src/locales/en/messages.json
  src/locales/es/desc.md
  src/locales/es/messages.json
  src/locales/ph/desc.md
  src/locales/ph/messages.json
  src/locales/pt/desc.md
  src/locales/pt/messages.json
  src/locales/zh/desc.md
  src/locales/zh/messages.json
  vue.config.js
  yarn.lock
Labels: size/L, 🔍 Ready for Review

#929 Update to what's new in 0.80.0
  src/locales/en/whats_new.json
Labels: size/XS, 🔍 Ready for Review

#932 Fix/manifest multilang
  src/locales/cb/pages.json
  src/locales/cb/whats_new.json
  src/locales/en/pages.json
  src/locales/es/pages.json
  src/locales/es/whats_new.json
  src/locales/ph/pages.json
  src/locales/ph/whats_new.json
  src/locales/pt/pages.json
  src/locales/pt/whats_new.json
  src/locales/zh/pages.json
  src/locales/zh/whats_new.json
  src/manifest.json
Labels: size/L, 🔍 Ready for Review

#934 Error fixes while adding a custom token
  src/views/CustomToken.vue
Labels: ✅ Approved, size/M

#935 Solana fees fix
  src/views/Swap/Swap.vue
Labels: ✅ Approved, size/M

#933 fix: localize error translations
  src/locales/cb/liquality_errors.json
  src/locales/en/components.json
  src/locales/en/liquality_errors.json
  src/locales/es/liquality_errors.json
  src/locales/ph/liquality_errors.json
  src/locales/pt/liquality_errors.json
  src/locales/zh/liquality_errors.json
  src/utils/localization.js
Labels: size/L, ✅ Approved

#936 Removing console logs
  src/views/Swap/Swap.vue
Labels: size/XS, 🔍 Ready for Review

#937 Activity filter fixes
  src/components/ActivityFilter.vue
  src/components/NoTransactionsFound.vue
  src/components/TransactionList.vue
  src/locales/en/common.json
  src/views/Wallet/WalletActivity.vue
Labels: ✅ Approved, size/M

#938 Update What's new for 0.81.0
  src/locales/cb/whats_new.json
  src/locales/en/whats_new.json
  src/locales/es/whats_new.json
  src/locales/ph/whats_new.json
  src/locales/pt/whats_new.json
  src/locales/zh/whats_new.json
Labels: size/L, ✅ Approved
