Repository liquality/wallet, pull requests merged in 2022-06, with the labels that each got.

#752 refactor: using enums instead of strings for chain names
  src/broker/terra-injection.js
  src/components/WalletAccounts.vue
  src/store/modules/app/requestPermission.js
  src/views/CustomToken.vue
  src/views/Send/Send.vue
Labels: 🔍 Ready for Review, size/M

#753 refactor: send fee
  src/components/CustomFeesEIP1559.vue
  src/views/CustomToken.vue
  src/views/Details/TransactionDetails.vue
  src/views/Send/Send.vue
Labels: ✅ Approved, size/M

#770 feat: prevent zero error for non dollar value assets
  src/views/Swap/Swap.vue
Labels: size/XS, ✅ Approved

#795 feat: improve minimum amount logic for boosts
  src/views/Swap/Swap.vue
Labels: 🔍 Ready for Review, size/M

#799 Automation tests for settings page
  .github/workflows/release.yml
  test/e2e/manage_accounts.spec.js
Labels: ✅ Approved, size/M

#801 feat: hotfix missing injection interface
  package.json
  src/inject.js
  src/manifest.json
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#803 Revert "feat: improve minimum amount logic for boosts"
  src/views/Swap/Swap.vue
Labels: ✅ Approved, size/M

#804 Revert "feat: prevent zero error for non dollar value assets"
  src/views/Swap/Swap.vue
Labels: size/XS, ✅ Approved

#805 Revert "refactor: send fee"
  src/components/CustomFeesEIP1559.vue
  src/views/CustomToken.vue
  src/views/Details/TransactionDetails.vue
  src/views/Send/Send.vue
Labels: ✅ Approved, size/M

#806 Revert "refactor: using enums instead of strings for chain names"
  src/broker/terra-injection.js
  src/components/WalletAccounts.vue
  src/store/modules/app/requestPermission.js
  src/views/CustomToken.vue
  src/views/Send/Send.vue
Labels: ✅ Approved, size/M

#784 Feat/chainify
  package.json
  src/background.js
  src/broker/terra-injection.js
  src/components/TransactionList.vue
  src/inject.js
  src/store/modules/app/executeRequest.js
  src/store/modules/app/handlePaymentUri.js
  src/store/modules/app/requestPermission.js
  src/swaps/views/Timeline.vue
  src/views/PermissionSign.vue
  src/views/Send/Send.vue
  src/views/Swap/Swap.vue
  test/e2e/dapp_injection_tests/avalanche_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/oneinch_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/uniswap_dapp_injection.spec.js
  test/unit/solana.test.js
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#807 Automation tests for activity tab
  package.json
  test/e2e/activity_page.spec.js
  test/pages/OverviewPage.js
  yarn.lock
Labels: size/XXL, ✅ Approved

#812 feat: set default to yes for analytics opt-in yes LIQ-1412
  src/components/AnalyticsOptInModal.vue
Labels: size/XS, ✅ Approved

#816 feat: LIQ-1470 - track create wallet and Import with seed phrase
  src/background.js
Labels: ✅ Approved, size/M

#817 fix: LIQ-1472 - Receive copy address chain property fix
  src/views/Receive.vue
Labels: size/XS, ✅ Approved

#810 fix: terra injection
  src/broker/terra-injection.js
  src/store/modules/app/executeRequest.js
Labels: size/S, ✅ Approved

#815 feat: change eip1559 calculation formula
  src/views/Details/TransactionDetails.vue
  src/views/PermissionSend.vue
  src/views/Send/Send.vue
  src/views/Swap/Swap.vue
Labels: size/S, 🔍 Ready for Review

#819 feat: updated wallet-core version in package json
  package.json
  yarn.lock
Labels: size/XL, 🔍 Ready for Review

#823 feat: addd priv-key-precommit
  .husky/pre-commit
  package.json
  yarn.lock
Labels: size/S, ✅ Approved

#824 feat: whats new model update
  package.json
  src/components/WhatsNewModal.vue
  yarn.lock
Labels: size/L, 🔍 Ready for Review
