Repository liquality/wallet, pull requests merged in 2022-04, with the labels that each got.

#741 Revert "feat: add Astroport in Boosts"
  src/build.config.js
  src/swaps/astroport/AstroportSwapProvider.js
  src/swaps/liqualityboost/liqualityBoostERC20toNative/LiqualityBoostERC20toNative.js
  src/swaps/liqualityboost/liqualityBoostNativeToERC20/LiqualityBoostNativeToERC20.js
  src/swaps/oneinch/OneinchSwapProvider.js
  src/utils/fees.js
Labels: 🔍 Ready for Review, size/M

#742 chore: Release candidate 0.59.0 into master
  .github/workflows/build-test-dev-mainnet.yml
  .github/workflows/build-test-prod-mainnet.yml
  .github/workflows/featureArtifact.yml
  .github/workflows/pullrequests.yml
  .github/workflows/release.yml
  package-lock.json
  package.json
  src/broker/terra-injection.js
  src/components/CustomFees.vue
  src/components/WatsNewModal.vue
  src/manifest.json
  src/store/migrations/18_enable_avalanche_chain.js
  src/store/mutations.js
  src/swaps/views/Timeline.vue
  src/utils/asset.js
  src/utils/coinFormatter.js
  src/views/Details/SwapDetails.vue
  src/views/PermissionSend.vue
  src/views/PermissionTerra.vue
  src/views/Send/Send.vue
  src/views/Send/SendInput.vue
  src/views/Swap/ReceiveInput.vue
  src/views/Swap/SendInput.vue
  src/views/Swap/Swap.vue
Labels: size/L, 🔍 Ready for Review

#743 fix: temporary disable erc20<>native boost swap
  src/build.config.js
Labels: size/XS, ✅ Approved

#746 fix: Release candidate 0.60.0
  package-lock.json
  package.json
  src/build.config.js
  src/manifest.json
Labels: size/XS, 🔍 Ready for Review

#755 fix: enable erc to native boost swaps
  src/build.config.js
Labels: size/XS, 🔍 Ready for Review

#744 fix: inccorect accountId on erc20 to native swaps
  src/swaps/liqualityboost/liqualityBoostERC20toNative/LiqualityBoostERC20toNative.js
Labels: size/XS, ✅ Approved

#748 fix: prevent account and asset chain mismatch
  src/store/getters.js
Labels: size/XS, 🔍 Ready for Review

#757 chore: hot fix release 0.61.0 into master
  package-lock.json
  package.json
  src/build.config.js
  src/components/WatsNewModal.vue
  src/manifest.json
  src/store/getters.js
  src/swaps/liqualityboost/liqualityBoostERC20toNative/LiqualityBoostERC20toNative.js
Labels: size/S, 🔍 Ready for Review

#758 fix: improved logic for amm validation
  src/views/Swap/Swap.vue
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#760 streamline onboarding experience
  src/broker/terra-injection.js
  src/components/AnalyticsOptInModal.vue
  src/views/Onboarding/OnboardingHome.vue
  test/pages/HomePage.js
  test/pages/PasswordPage.js
Labels: size/L, ✅ Approved
