Repository liquality/wallet, pull requests merged in 2022-03, with the labels that each got.

#694 fix: Min swap rate for astroport
  src/swaps/astroport/AstroportSwapProvider.js
  src/views/Swap/Swap.vue
Labels: 🔍 Ready for Review, size/M

#685 feat: boost provider erc20 to native release
  package-lock.json
  src/build.config.js
  src/store/actions/performNextAction/index.js
  src/store/factory/swapProvider.js
  src/store/getters.js
  src/swaps/liquality/LiqualitySwapProvider.js
  src/swaps/liqualityboost/liqualityBoostERC20toNative/LiqualityBoostERC20toNative.js
  src/swaps/liqualityboost/liqualityBoostERC20toNative/info.json
  src/swaps/liqualityboost/liqualityBoostNativeToERC20/LiqualityBoostNativeToERC20.js
  src/swaps/liqualityboost/liqualityBoostNativeToERC20/info.json
  src/swaps/sovryn/SovrynSwapProvider.js
  src/swaps/views/Timeline.vue
  src/utils/swaps.js
  src/views/Swap/Swap.vue
Labels: size/L, ✅ Approved

#697 fix: fix lint issues
  src/swaps/astroport/AstroportSwapProvider.js
Labels: size/XS, ✅ Approved

#681 feat: rework timeline screen
  src/swaps/views/Timeline.vue
  src/transactions/views/Timeline.vue
  src/views/Details/SwapDetails.vue
Labels: size/L, 🔍 Ready for Review

#699 feat: Update CAL packages to 1.13.9
  package-lock.json
  package.json
Labels: 🔍 Ready for Review, size/M

#698 feat: Update terra node
  .github/workflows/featureArtifact.yml
  .github/workflows/pullrequests.yml
  .github/workflows/release.yml
  src/store/factory/client.js
Labels: size/S, 🔍 Ready for Review

#700 fix: Gas limit on terra
  src/swaps/liquality/LiqualitySwapProvider.js
Labels: size/S, 🔍 Ready for Review, ✅ Approved

#701 fix: Hide menu settings when user click on Connect Dapp
  src/components/Head.vue
  src/components/NavBar.vue
  src/store/modules/app/actions.js
  src/store/modules/app/getters.js
  src/store/modules/app/mutations.js
  src/store/modules/app/state.js
Labels: 🔍 Ready for Review, size/M

#683 feat: add avalanche in liquality wallet
  src/assets/icons/assets/avax.svg
  src/assets/icons/assets/avax_account.svg
  src/build.config.js
  src/store/factory/client.js
  src/store/getters.js
  src/store/migrations/18_enable_avalanche_chain.js
  src/store/migrations/index.js
  src/swaps/liquality/LiqualitySwapProvider.js
  src/swaps/oneinch/OneinchSwapProvider.js
  src/swaps/oneinch/info.json
  src/utils/accounts.js
  src/utils/asset.js
  src/utils/derivationPath.js
  src/utils/fees.js
  src/utils/networks.js
  src/views/CustomToken.vue
  src/views/Receive.vue
  test/e2e/add_custom_token.spec.js
  test/e2e/import_wallet.spec.js
  test/e2e/manage_accounts.spec.js
  test/e2e/receive_assets.spec.js
  test/e2e/rsk_tests/derived_path.spec.js
  test/e2e/send_transaction.spec.js
  test/e2e/service_provider_tests/liquality_atomic_swaps.spec.js
  test/pages/OverviewPage.js
Labels: size/XL, ✅ Approved

#704 feat: Add memo input for terra
  package-lock.json
  package.json
  src/views/Send/Send.vue
Labels: size/L, 🔍 Ready for Review

#709 feat: enabled boostprovider for avax
  src/build.config.js
  src/swaps/liqualityboost/liqualityBoostERC20toNative/LiqualityBoostERC20toNative.js
  src/swaps/liqualityboost/liqualityBoostNativeToERC20/LiqualityBoostNativeToERC20.js
Labels: size/S, ✅ Approved

#711 feat: Set avalanche moralis rpc node
  .env
  .github/workflows/build-test-dev-mainnet.yml
  .github/workflows/build-test-prod-mainnet.yml
  .github/workflows/featureArtifact.yml
  .github/workflows/pullrequests.yml
  .github/workflows/release.yml
  src/build.config.js
  src/store/factory/client.js
Labels: ✅ Approved, size/M

#714 fix: NEAR ankr mainnet endpoint updated
  src/store/factory/client.js
Labels: size/XS, ✅ Approved

#716 fix: Hotfix NEAR & TERRA figment endpoints updated
  .env
  .github/workflows/release.yml
  package-lock.json
  package.json
  src/store/factory/client.js
Labels: size/S, 🔍 Ready for Review, 🌟 Needs more Approvals

#710 fix: NaN and timeline on terra
  src/broker/terra-injection.js
  src/views/PermissionTerra.vue
Labels: ✅ Approved, size/M

#729 fix: updated migration version of avalanche
  src/store/migrations/18_enable_avalanche_chain.js
Labels: size/XS, ✅ Approved

#722 Liq 1068 format send amount
  src/views/PermissionSend.vue
Labels: size/XS, ✅ Approved

#717 fix: show erro message when eth is not enough to cover withdraw fee
  src/views/Swap/Swap.vue
Labels: size/S, 🔍 Ready for Review

#719 fix: scientific values removed from ui
  src/components/CustomFees.vue
  src/views/Send/Send.vue
  src/views/Swap/Swap.vue
Labels: 🔍 Ready for Review, size/M

#720 feat: Reverse assets on arrow click and keep same from amount on asset change
  src/views/Swap/ReceiveInput.vue
  src/views/Swap/SendInput.vue
  src/views/Swap/Swap.vue
Labels: ✅ Approved, size/M

#730 fix: avalanche migration version
  src/store/migrations/18_enable_avalanche_chain.js
  src/views/Swap/Swap.vue
Labels: size/S, 🔍 Ready for Review

#724 feat: add Astroport in Boosts
  src/build.config.js
  src/swaps/astroport/AstroportSwapProvider.js
  src/swaps/liqualityboost/liqualityBoostERC20toNative/LiqualityBoostERC20toNative.js
  src/swaps/liqualityboost/liqualityBoostNativeToERC20/LiqualityBoostNativeToERC20.js
  src/swaps/oneinch/OneinchSwapProvider.js
  src/utils/fees.js
Labels: 🔍 Ready for Review, size/M

#728 fix: correct deafult asset logic
  src/store/mutations.js
  src/utils/asset.js
  src/views/Swap/Swap.vue
Labels: 🔍 Ready for Review, size/M
