Repository liquality/wallet, pull requests merged in 2022-05, with the labels that each got.

#767 Improve minimal amounts
  src/views/Swap/Swap.vue
  src/views/Swap/SwapInfo.vue
Labels: size/S, ✅ Approved

#769 fix: Locked wallet should show password screen
  src/views/Splash.vue
Labels: size/XS, ✅ Approved

#739 fix: remove duplicate providers on info modal
  src/views/Swap/SwapProvidersInfoModal.vue
Labels: size/XS, ✅ Approved

#776 feat: use yarn@3.1.1
  .github/workflows/build-test-dev-mainnet.yml
  .github/workflows/build-test-prod-mainnet.yml
  .github/workflows/featureArtifact.yml
  .github/workflows/pullrequests.yml
  .github/workflows/release.yml
  .gitignore
  .yarn/releases/yarn-3.1.1.cjs
  .yarnrc.yml
  package-lock.json
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#777 feat: Update wallet core to 1.4.34
  package.json
  yarn.lock
Labels: size/S, 🔍 Ready for Review

#778 fix: Remove version check for Prod because we will publish prod walle…
  .github/workflows/release.yml
Labels: ✅ Approved, size/M

#780 chore: Release candidate 0.62.1
  .github/workflows/build-test-dev-mainnet.yml
  .github/workflows/build-test-prod-mainnet.yml
  .github/workflows/featureArtifact.yml
  .github/workflows/pullrequests.yml
  .github/workflows/release.yml
  .gitignore
  .yarn/releases/yarn-3.1.1.cjs
  .yarnrc.yml
  package-lock.json
  package.json
  src/background.js
  src/components/WatsNewModal.vue
  src/manifest.json
  src/views/Account.vue
  src/views/Splash.vue
  src/views/Swap/SwapProvidersInfoModal.vue
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#779 refactor: Use timeline from wallet-core
  package.json
  src/swaps/views/Timeline.vue
  yarn.lock
Labels: size/L, 🔍 Ready for Review

#771 feat: show error when bridge asset of boost is disabled
  src/components/BoostActivateBridgeAsset.vue
  src/views/Swap/Swap.vue
Labels: 🔍 Ready for Review, size/M

#781 feat: Release candidate 0.62.2.
  package.json
  src/background.js
  src/components/ConnectionDrawer.vue
  src/components/NavBar.vue
  src/views/Account.vue
  src/views/Accounts/HardwareWallet/HardwareWallet.vue
  src/views/Onboarding/SeedPhrase/LoginPhrase.vue
  src/views/Receive.vue
  src/views/Send/Send.vue
  src/views/Settings.vue
  src/views/Swap/Swap.vue
  src/views/UnlockWallet.vue
  yarn.lock
Labels: size/L, 🔍 Ready for Review, 🌟 Needs more Approvals

#775 feat: integrate hop exchange in wallet
  package.json
  src/assets/icons/assets/arbdai.svg
  src/assets/icons/assets/arbusdc.svg
  src/assets/icons/assets/arbusdt.svg
  src/assets/icons/swapProviders/hop.svg
  src/views/Send/Send.vue
  src/views/Swap/Swap.vue
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#783 feat: updated logo hop provider
  .github/workflows/pullrequests.yml
  package.json
  src/assets/icons/swapProviders/hop.svg
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#764 componentize `copy address` tooltip
  src/assets/icons/check-primary.svg
  src/components/CopyAddress.vue
  src/views/Account.vue
Labels: size/L, 🔍 Ready for Review

#787 fix: Update wallet core - fixes market data failing
  package.json
  yarn.lock
Labels: size/S, 🔍 Ready for Review

#786 fix: temporary solution to ensure transaction fee is covered when max…
  src/views/Swap/Swap.vue
Labels: size/XS, ✅ Approved

#788 feat: Merge 0.63.0 into master
  .github/workflows/pullrequests.yml
  .github/workflows/release.yml
  package.json
  src/assets/icons/assets/arbdai.svg
  src/assets/icons/assets/arbusdc.svg
  src/assets/icons/assets/arbusdt.svg
  src/assets/icons/check-primary.svg
  src/assets/icons/swapProviders/hop.svg
  src/background.js
  src/components/BoostActivateBridgeAsset.vue
  src/components/CopyAddress.vue
  src/components/WatsNewModal.vue
  src/swaps/views/Timeline.vue
  src/views/Account.vue
  src/views/Receive.vue
  src/views/Send/Send.vue
  src/views/Swap/Swap.vue
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#791 Fix/height of message
  src/views/PermissionSign.vue
Labels: size/XS, ✅ Approved

#790 Automation tests for Hop
  .gitignore
  test/e2e/hop_tests/hop_swaps.spec.js
Labels: size/L, ✅ Approved
