Repository liquality/wallet, pull requests merged in 2022-07, with the labels that each got.

#830 fix: seed confirmation with repeating words
  src/views/Onboarding/OnboardingSetup.vue
  src/views/Onboarding/SeedPhrase/ConfirmSeed.vue
Labels: size/S, ✅ Approved

#820 fix: ensure injection without default web3. more reliable
  src/contentScript.js
  src/inject.js
Labels: size/S, ✅ Approved

#814 feat: add eip1559 for polygon & avalanche
  src/views/PermissionSend.vue
  src/views/Send/Send.vue
  src/views/Swap/Swap.vue
  yarn.lock
Labels: size/L, 🔍 Ready for Review

#712 Feature remove ledger bridge
  .nvmrc
  .yarn/install-state.gz
  package.json
  src/App.vue
  src/assets/scss/style.scss
  src/components/HeadMenu.vue
  src/components/LedgerBridgeModal.vue
  src/components/LedgerTabBanner.vue
  src/components/Modal.vue
  src/components/NavBar.vue
  src/core.js
  src/router/index.js
  src/store/modules/app/actions.js
  src/store/modules/app/executeRequest.js
  src/store/modules/app/getters.js
  src/store/modules/app/requestPermission.js
  src/utils/hardware-wallet.js
  src/utils/ledger-bridge-provider/BitcoinLedgerBridgeApp.js
  src/utils/ledger-bridge-provider/BitcoinLedgerBridgeProvider.js
  src/utils/ledger-bridge-provider/EthereumLedgerBridgeApp.js
  src/utils/ledger-bridge-provider/EthereumLedgerBridgeProvider.js
  src/utils/ledger-bridge-provider/LedgerBridgeApp.js
  src/utils/ledger-bridge-provider/index.js
  src/utils/ledger-bridge-provider/utils.js
  src/views/Account.vue
  src/views/Accounts/HardwareWallet/Completed.vue
  src/views/Accounts/HardwareWallet/Connect.vue
  src/views/Accounts/HardwareWallet/HardwareWallet.vue
  src/views/Accounts/HardwareWallet/Unlock.vue
  src/views/Details/SwapDetails.vue
  src/views/PermissionSend.vue
  src/views/PermissionSign.vue
  src/views/PermissionSignPsbt.vue
  src/views/Send/Send.vue
  src/views/Swap/Swap.vue
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#833 fix: text shorten issue
  src/views/Swap/Swap.vue
  src/views/Swap/SwapInfo.vue
Labels: size/S, ✅ Approved

#832 fix: fixed permission sign views + ledger
  .yarn/install-state.gz
  src/views/Accounts/HardwareWallet/HardwareWallet.vue
  src/views/PermissionSign.vue
  src/views/PermissionSignPsbt.vue
Labels: size/S, 🔍 Ready for Review

#834 fix: fixed default fee and swap provider types modal height
  src/components/Modal.vue
  src/views/Swap/Swap.vue
  src/views/Swap/SwapProvidersInfoModal.vue
Labels: size/S, ✅ Approved

#835 test: buy crypto tests OPS-3
  test/e2e/transak_tests/new_wallet_user_buy_crypto.spec.js
Labels: size/S, 🔍 Ready for Review

#836 feat: Release candidate 0.67.0
  .github/workflows/build-test-dev-mainnet.yml
  .github/workflows/build-test-prod-mainnet.yml
  .github/workflows/release.yml
  .nvmrc
  package.json
  src/App.vue
  src/assets/scss/style.scss
  src/background.js
  src/components/HeadMenu.vue
  src/components/LedgerBridgeModal.vue
  src/components/LedgerTabBanner.vue
  src/components/Modal.vue
  src/components/NavBar.vue
  src/components/WhatsNewModal.vue
  src/contentScript.js
  src/core.js
  src/inject.js
  src/manifest.json
  src/router/index.js
  src/store/modules/app/actions.js
  src/store/modules/app/executeRequest.js
  src/store/modules/app/getters.js
  src/store/modules/app/requestPermission.js
  src/utils/hardware-wallet.js
  src/utils/ledger-bridge-provider/BitcoinLedgerBridgeApp.js
  src/utils/ledger-bridge-provider/BitcoinLedgerBridgeProvider.js
  src/utils/ledger-bridge-provider/EthereumLedgerBridgeApp.js
  src/utils/ledger-bridge-provider/EthereumLedgerBridgeProvider.js
  src/utils/ledger-bridge-provider/LedgerBridgeApp.js
  src/utils/ledger-bridge-provider/index.js
  src/utils/ledger-bridge-provider/utils.js
  src/views/Account.vue
  src/views/Accounts/HardwareWallet/Completed.vue
  src/views/Accounts/HardwareWallet/Connect.vue
  src/views/Accounts/HardwareWallet/HardwareWallet.vue
  src/views/Accounts/HardwareWallet/Unlock.vue
  src/views/Details/SwapDetails.vue
  src/views/ManageAssets.vue
  src/views/Onboarding/OnboardingSetup.vue
  src/views/Onboarding/SeedPhrase/ConfirmSeed.vue
  src/views/PermissionSend.vue
  src/views/PermissionSign.vue
  src/views/PermissionSignPsbt.vue
  src/views/Send/Send.vue
  src/views/Swap/Swap.vue
  src/views/Swap/SwapInfo.vue
  src/views/Swap/SwapProvidersInfoModal.vue
  test/e2e/dapp_injection_tests/uniswap_dapp_injection.spec.js
  test/e2e/manage_accounts.spec.js
  test/e2e/rsk_tests/rsk_sovryn_amm.spec.js
  test/e2e/service_provider_tests/thorechain_swaps.spec.js
  test/e2e/terra_tests/terra_astroport_amm.spec.js
  test/e2e/transak_tests/new_wallet_user_buy_crypto.spec.js
  test/pages/OverviewPage.js
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#808 fix: get rid of duplicate balance update dispatching
  src/background.js
Labels: size/XS, ✅ Approved

#831 Feat/enable account when native or erc20 get enabled
  src/views/CustomToken.vue
  src/views/ManageAssets.vue
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#826 feat: implemented onramper widget integration
  .env
  src/assets/icons/onramper-logo.png
  src/components/BuyCrypto/BuyCryptoModal.vue
  src/components/BuyCrypto/BuyCryptoOverviewModal.vue
  src/components/BuyCrypto/BuyCryptoProviderBrand.vue
  src/store/modules/app/actions.js
  src/views/AssetList.vue
  src/views/Receive.vue
Labels: size/L, 🔍 Ready for Review

#839 fix: remove unused spacing on notifications
  src/components/BoostActivateBridgeAsset.vue
  src/components/BridgeAssetRequiredMessage.vue
  src/components/CannotCoverMinimumMessage.vue
  src/components/EthRequiredMessage.vue
  src/components/LedgerRequestMessage.vue
  src/components/NoFundsForNetworkFee.vue
Labels: size/S, ✅ Approved

#842 fix: check for initial load on balances
  src/components/WalletAccounts.vue
Labels: size/S, ✅ Approved

#843 chore: merge release candidate 0.68.0 to master
  .env
  .github/workflows/release.yml
  package.json
  src/assets/icons/onramper-logo.png
  src/background.js
  src/components/BoostActivateBridgeAsset.vue
  src/components/BridgeAssetRequiredMessage.vue
  src/components/BuyCrypto/BuyCryptoModal.vue
  src/components/BuyCrypto/BuyCryptoOverviewModal.vue
  src/components/BuyCrypto/BuyCryptoProviderBrand.vue
  src/components/CannotCoverMinimumMessage.vue
  src/components/EthRequiredMessage.vue
  src/components/LedgerRequestMessage.vue
  src/components/NoFundsForNetworkFee.vue
  src/components/WalletAccounts.vue
  src/components/WhatsNewModal.vue
  src/manifest.json
  src/store/modules/app/actions.js
  src/views/AssetList.vue
  src/views/CustomToken.vue
  src/views/ManageAssets.vue
  src/views/Receive.vue
  src/views/Swap/Swap.vue
  src/views/Swap/SwapInfo.vue
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#838 fix: removed outdated validation
  src/views/Swap/Swap.vue
Labels: size/XS, ✅ Approved

#841 feat: enable ledger swaps
  src/views/Account.vue
  src/views/AssetList.vue
  src/views/Swap/Accounts.vue
  src/views/Swap/Swap.vue
Labels: size/L, 🔍 Ready for Review
