Repository liquality/wallet, pull requests merged in 2022-09, with the labels that each got.

#866 chore: merge 0.72.0 into master
  .env
  .github/workflows/build-test-prod-mainnet.yml
  .github/workflows/release.yml
  package.json
  src/assets/icons/assets/bond.svg
  src/assets/icons/assets/df.svg
  src/assets/icons/assets/dht.svg
  src/assets/icons/assets/lusd.svg
  src/assets/icons/assets/mask.svg
  src/assets/icons/assets/optimism.svg
  src/assets/icons/assets/paper.svg
  src/assets/icons/assets/rai.svg
  src/assets/icons/assets/sbtc.svg
  src/assets/icons/assets/seth.svg
  src/assets/icons/assets/slink.svg
  src/assets/icons/assets/susd.svg
  src/assets/icons/assets/usx.svg
  src/assets/icons/assets/weth.svg
  src/assets/icons/stratosnft.svg
  src/background.js
  src/components/ActivityFilter.vue
  src/components/CustomFeesEIP1559.vue
  src/components/NFT/NFTAsset.vue
  src/components/NFT/NFTAssets.vue
  src/components/NFT/NFTQuantity.vue
  src/components/NFT/NFTTimeline.vue
  src/components/NFT/Star.vue
  src/components/WhatsNewModal.vue
  src/inject.js
  src/manifest.json
  src/transactions/views/Timeline.vue
  src/utils/accounts.js
  src/utils/asset.js
  src/views/Account.vue
  src/views/CustomToken.vue
  src/views/Details/NFTAssetDetails.vue
  src/views/Details/NFTCollectionList.vue
  src/views/Details/NFTTransactionDetails.vue
  src/views/Details/SwapDetails.vue
  src/views/Details/TransactionDetails.vue
  src/views/PermissionSend.vue
  src/views/PermissionTerra.vue
  src/views/Receive.vue
  src/views/Send/Send.vue
  src/views/Send/SendNFT.vue
  src/views/Swap/Swap.vue
  src/views/Wallet/NFTActivity.vue
  src/views/Wallet/NFTStats.vue
  src/views/Wallet/Wallet.vue
  src/views/Wallet/WalletActivity.vue
  src/views/Wallet/WalletNFTs.vue
  test/e2e/rsk_tests/derived_path.spec.js
  test/pages/OverviewPage.js
  test/pages/SendPage.js
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#869 Automation tests for solana swaps
  test/e2e/solana_tests/solana_swaps.spec.js
Labels: size/L, 🔍 Ready for Review, ✅ Approved

#861 feat: use new cryptoassets
  .github/workflows/pullrequests.yml
  package.json
  src/broker/Background.js
  src/components/AccountTooltip.vue
  src/components/ChainDropdown.vue
  src/components/ConnectionDrawer.vue
  src/components/CustomFees.vue
  src/components/CustomFeesEIP1559.vue
  src/components/FeeSelector.vue
  src/components/NFT/NFTTimeline.vue
  src/contentScript.js
  src/store/modules/app/actions.js
  src/store/modules/app/executeRequest.js
  src/swaps/views/Timeline.vue
  src/transactions/views/Timeline.vue
  src/views/Account.vue
  src/views/Accounts/Create.vue
  src/views/Accounts/HardwareWallet/Connect.vue
  src/views/Accounts/Manage.vue
  src/views/Details/NFTAssetDetails.vue
  src/views/Details/NFTTransactionDetails.vue
  src/views/Details/SwapDetails.vue
  src/views/Details/TransactionDetails.vue
  src/views/Enable.vue
  src/views/PermissionSend.vue
  src/views/PermissionSignPsbt.vue
  src/views/Receive.vue
  src/views/Send/Send.vue
  src/views/Send/SendNFT.vue
  src/views/Swap/Swap.vue
  src/views/Wallet/NFTActivity.vue
  src/views/Wallet/NFTStats.vue
  src/views/Wallet/WalletNFTs.vue
  test/e2e/dapp_injection_tests/avalanche_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/oneinch_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/rsk_sovryn_injection.spec.js
  test/e2e/dapp_injection_tests/rsk_sovryn_injection_create_wallet.spec.js
  test/e2e/dapp_injection_tests/sushi_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/terra_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/uniswap_dapp_injection.spec.js
  test/e2e/enable_disable_assets.spec.js
  test/e2e/hop_tests/hop_swaps.spec.js
  test/e2e/manage_accounts.spec.js
  test/e2e/receive_assets.spec.js
  test/e2e/rsk_tests/derived_path.spec.js
  test/e2e/rsk_tests/fastbtc_swap.spec.js
  test/e2e/send_transaction.spec.js
  test/e2e/service_provider_tests/liquality_atomic_swaps.spec.js
  test/e2e/service_provider_tests/oneinch_swap_provider.spec.js
  test/e2e/service_provider_tests/thorechain_swaps.spec.js
  test/pages/HomePage.js
  test/pages/OverviewPage.js
  test/utils/TestDataUtils.js
  yarn.lock
Labels: size/XL, 🔍 Ready for Review

#871 test: some test updates
  .github/workflows/build-test-prod-mainnet.yml
  .github/workflows/featureArtifact.yml
  .github/workflows/pullrequests.yml
  .github/workflows/release.yml
  package.json
  test/e2e/custom_fee.spec.js
  test/e2e/dapp_injection_tests/rsk_sovryn_injection.spec.js
  test/e2e/dapp_injection_tests/rsk_sovryn_injection_create_wallet.spec.js
  test/e2e/dapp_injection_tests/uniswap_dapp_injection.spec.js
  test/e2e/hop_tests/hop_swaps.spec.js
  test/e2e/receive_assets.spec.js
  test/e2e/rsk_tests/fastbtc_swap.spec.js
  test/e2e/rsk_tests/rsk_sovryn_amm.spec.js
  test/e2e/send_transaction.spec.js
  test/e2e/service_provider_tests/oneinch_swap_provider.spec.js
  test/e2e/service_provider_tests/uniswap_provider.spec.js
  test/e2e/solana_tests/solana_swaps.spec.js
  test/e2e/swap_tests/rbtc_btc_swap.spec.js
  test/e2e/terra_tests/terra_astroport_amm.spec.js
  test/e2e/terra_tests/terra_custom_token.spec.js
  test/e2e/terra_tests/terra_send.spec.js
  test/e2e/terra_tests/terra_swaps.spec.js
  test/pages/OverviewPage.js
  test/pages/SendPage.js
Labels: size/L, 🔍 Ready for Review

#870 NFT Updates
  src/views/Details/NFTCollectionList.vue
  src/views/Swap/Accounts.vue
Labels: size/S, ✅ Approved

#868 Automation tests for Onramper
  test/e2e/onramper_tests/onramper_buy_crypto.spec.js
Labels: size/L, 🔍 Ready for Review

#867 Injection in JS with modules
  .mocharc.yml
  plugins/AssetReplacePlugin.js
  src/broker/utils.js
  src/contentScript.js
  src/inject.js
  src/pageProvider/bitcoinProvider.js
  src/pageProvider/ethereumProvider.js
  src/pageProvider/globalEthereumProvider.js
  src/pageProvider/index.js
  src/pageProvider/nearProvider.js
  src/pageProvider/pageProvider.js
  src/pageProvider/paymentUri.js
  src/pageProvider/providerManager.js
  src/pageProvider/solanaProvider.js
  src/pageProvider/terraProvider.js
  src/pageProvider/utils.js
  test/e2e/dapp_injection_tests/avalanche_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/oneinch_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/rsk_sovryn_injection.spec.js
  test/e2e/dapp_injection_tests/sushi_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/terra_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/uniswap_dapp_injection.spec.js
  test/pages/OverviewPage.js
  test/pages/PasswordPage.js
  vue.config.js
Labels: size/XXL, 🔍 Ready for Review

#875 fix: remove split chunks in prod
  vue.config.js
Labels: size/S, 🔍 Ready for Review

#877 fix: fixed ledger create account flow
  package.json
  src/components/FeeSelector.vue
  src/components/WalletAccounts.vue
  src/swaps/views/Timeline.vue
  src/transactions/views/Timeline.vue
  src/views/Accounts/Create.vue
  src/views/Accounts/HardwareWallet/HardwareWallet.vue
  src/views/Details/NFTTransactionDetails.vue
  src/views/Details/SwapDetails.vue
  src/views/PermissionSend.vue
  src/views/Send/Send.vue
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#876 fix: timeline diagram for non-evm chains
  src/transactions/views/Timeline.vue
Labels: size/S, ✅ Approved

#878 fix: hide export private key option for Bitcoin accounts
  src/components/NavBar.vue
Labels: size/S, 🔍 Ready for Review

#881 Ext 77 network fee is always zero in nft send
  src/views/Details/NFTAssetDetails.vue
  src/views/Send/SendNFT.vue
Labels: size/XS, ✅ Approved
