Repository liquality/wallet, pull requests merged in 2022-02, with the labels that each got.

#642 fix: Hide eip1559 for Matic on mainnet
  src/views/PermissionSend.vue
  src/views/Send/Send.vue
  src/views/Swap/Swap.vue
Labels: size/XS, 🔍 Ready for Review

#644 fix: added error handling on thorchain swap
  src/swaps/thorchain/ThorchainSwapProvider.js
Labels: size/XS, 🔍 Ready for Review, 🌟 Needs more Approvals

#646 fix/add-default-value-if-fee-is-undefined
  src/components/CustomFeesEIP1559.vue
Labels: size/S, 🔍 Ready for Review, 🌟 Needs more Approvals

#645 fix: update CAL - matic confirmation property
  package-lock.json
  package.json
Labels: 🔍 Ready for Review, size/M

#648 fix: thorchain memo was wrong
  src/swaps/thorchain/ThorchainSwapProvider.js
Labels: size/XS, ✅ Approved

#650 fix/liq-1039-thorchain-nan-fee-btc-usdt-swap
  src/views/Swap/Swap.vue
Labels: size/XS, ✅ Approved

#647 feat: Connection request - auto select most popular chain
  package-lock.json
  package.json
  src/views/Enable.vue
  src/views/Receive.vue
Labels: size/S, ✅ Approved

#653 feat: LIQ-1049, swap history send provider
  src/background.js
Labels: size/S, 🔍 Ready for Review, 🌟 Needs more Approvals

#660 feat: Update cryptoassets to 1.7.5
  package-lock.json
  package.json
Labels: size/XS, 🔍 Ready for Review

#661 feat: Add images for new tokens on terra
  src/assets/icons/assets/abr.svg
  src/assets/icons/assets/alot.svg
  src/assets/icons/assets/astro.svg
  src/assets/icons/assets/bpsidp-24m.svg
  src/assets/icons/assets/btl.svg
  src/assets/icons/assets/glow.svg
  src/assets/icons/assets/halo.svg
  src/assets/icons/assets/kuji.svg
  src/assets/icons/assets/lunax.svg
  src/assets/icons/assets/luni.svg
  src/assets/icons/assets/moon.svg
  src/assets/icons/assets/orne.svg
  src/assets/icons/assets/ply.svg
  src/assets/icons/assets/prism.svg
  src/assets/icons/assets/pug.svg
  src/assets/icons/assets/sdollar.svg
  src/assets/icons/assets/sity.svg
  src/assets/icons/assets/stluna.svg
  src/assets/icons/assets/tfloki.svg
  src/assets/icons/assets/tftic.svg
  src/assets/icons/assets/tfticii.svg
  src/assets/icons/assets/tfticiii.svg
  src/assets/icons/assets/tland.svg
  src/assets/icons/assets/wbbnb.svg
  src/assets/icons/assets/wbcake.svg
  src/assets/icons/assets/webeth.svg
  src/assets/icons/assets/weldo.svg
  src/assets/icons/assets/welink.svg
  src/assets/icons/assets/wematic.svg
  src/assets/icons/assets/wesol.svg
  src/assets/icons/assets/wesushi.svg
  src/assets/icons/assets/weusdc.svg
  src/assets/icons/assets/weusdt.svg
  src/assets/icons/assets/wewbtc.svg
  src/assets/icons/assets/weweth.svg
  src/assets/icons/assets/wewsteth.svg
  src/assets/icons/assets/whgsail.svg
  src/assets/icons/assets/whsail.svg
  src/assets/icons/assets/wsstsol.svg
  src/assets/icons/assets/xdefi.svg
  src/assets/icons/assets/xprism.svg
  src/assets/icons/assets/xrune.svg
Labels: 🔍 Ready for Review, 🌟 Needs more Approvals, size/M

#663 chore: Dev 0.54.4
  .github/workflows/build-test-dev-mainnet.yml
  .github/workflows/build-test-prod-mainnet.yml
  package-lock.json
  package.json
  src/manifest.json
  src/views/Account.vue
  src/views/Swap/Swap.vue
  test/e2e/03_receive.spec.js
  test/e2e/09_menu_options.spec.js
  test/e2e/16_uniswap_provider.spec.js
  test/e2e/19_private_keys_export.spec.js
  test/e2e/terra_tests/19_terra_send.spec.js
  test/e2e/terra_tests/23_terra_custom_token.spec.js
Labels: 🔍 Ready for Review, size/M

#472 feat: Epic reboot ledger
  package-lock.json
  src/assets/scss/_overrides.scss
  src/assets/scss/style.scss
  src/background.js
  src/components/NavBar.vue
  src/manifest.json
  src/store/actions/accounts/createAccount.js
  src/store/actions/executeRequest.js
  src/store/actions/getUnusedAddresses.js
  src/store/actions/hardware-wallet/getLedgerAccounts.js
  src/store/actions/updateAccountBalance.js
  src/store/actions/updateBalances.js
  src/store/actions/updateTransactionFee.js
  src/store/factory/client.js
  src/store/getters.js
  src/store/index.js
  src/store/migrations/17_remove_existing_ledger_accounts.js
  src/store/migrations/index.js
  src/store/modules/app/actions.js
  src/store/modules/app/mutations.js
  src/store/modules/app/state.js
  src/swaps/fastbtc/FastbtcSwapProvider.js
  src/swaps/views/Timeline.vue
  src/utils/accounts.js
  src/utils/coinFormatter.js
  src/utils/ledger-bridge-provider/BitcoinLedgerBridgeApp.js
  src/utils/ledger-bridge-provider/BitcoinLedgerBridgeProvider.js
  src/utils/ledger-bridge-provider/EthereumLedgerBridgeApp.js
  src/utils/ledger-bridge-provider/config.js
  src/utils/ledger-bridge-provider/utils.js
  src/views/Account.vue
  src/views/Accounts/HardwareWallet/Connect.vue
  src/views/Accounts/HardwareWallet/HardwareWallet.vue
  src/views/Accounts/HardwareWallet/Unlock.vue
  src/views/AssetList.vue
  src/views/Details/SwapDetails.vue
  src/views/Details/TransactionDetails.vue
  src/views/Receive.vue
  src/views/Send/Send.vue
  src/views/Swap/Accounts.vue
  src/views/Swap/Swap.vue
Labels: size/XL, 🔍 Ready for Review

#671 fix: default web3 remove dapp toggle
  .github/workflows/build-test-dev-mainnet.yml
  .github/workflows/build-test-prod-mainnet.yml
  .github/workflows/pullrequests.yml
  package-lock.json
  src/components/ConnectionDrawer.vue
  src/components/Head.vue
  src/components/WatsNewModal.vue
  src/contentScript.js
  src/store/migrations/17_remove_injection_enabled.js
  src/store/migrations/index.js
  src/store/mutations.js
  src/store/state.js
  test/e2e/dapp_injection_tests/oneinch_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/rsk_sovryn_injection.spec.js
  test/e2e/dapp_injection_tests/sushi_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/terra_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/uniswap_dapp_injection.spec.js
  test/e2e/manage_accounts.spec.js
  test/pages/OverviewPage.js
Labels: ✅ Approved, size/M

#674 chore: Release candidate 0.55.0
  .github/workflows/build-test-dev-mainnet.yml
  .github/workflows/build-test-prod-mainnet.yml
  .github/workflows/pullrequests.yml
  package-lock.json
  package.json
  src/components/ConnectionDrawer.vue
  src/components/Head.vue
  src/components/WatsNewModal.vue
  src/contentScript.js
  src/manifest.json
  src/store/migrations/17_remove_injection_enabled.js
  src/store/migrations/index.js
  src/store/mutations.js
  src/store/state.js
  test/e2e/dapp_injection_tests/oneinch_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/rsk_sovryn_injection.spec.js
  test/e2e/dapp_injection_tests/sushi_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/terra_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/uniswap_dapp_injection.spec.js
  test/e2e/import_wallet.spec.js
  test/e2e/manage_accounts.spec.js
  test/pages/OverviewPage.js
Labels: 🔍 Ready for Review, size/M

#680 feat: Astroport swap provider
  .github/workflows/featureArtifact.yml
  .github/workflows/pullrequests.yml
  .github/workflows/release.yml
  package-lock.json
  package.json
  src/assets/icons/swapProviders/astroport.svg
  src/background.js
  src/build.config.js
  src/store/factory/swapProvider.js
  src/swaps/astroport/AstroportSwapProvider.js
  src/swaps/astroport/info.json
  src/swaps/astroport/queries.js
  src/utils/swaps.js
  src/views/Swap/SwapProvidersInfoModal.vue
  test/e2e/dapp_injection_tests/oneinch_dapp_injection.spec.js
  test/e2e/dapp_injection_tests/sushi_dapp_injection.spec.js
  test/e2e/terra_tests/terra_astroport_amm.spec.js
Labels: size/XXL, ✅ Approved

#676 fix: prevent disconnections from breaking injection
  src/broker/Background.js
Labels: ✅ Approved, size/M

#682 fix: Export data
  src/components/ActivityFilter.vue
Labels: size/S, ✅ Approved

#686 feat: Update-cryptoassets-1.10.0
  package-lock.json
  package.json
Labels: size/XS, ✅ Approved

#687 fix: Send max on terra
  .github/workflows/pullrequests.yml
  src/store/factory/client.js
  src/swaps/astroport/queries.js
  src/swaps/liquality/LiqualitySwapProvider.js
  src/views/Send/Send.vue
Labels: 🔍 Ready for Review, size/M

#691 fix: getting quote throw appropriate error
  src/swaps/liquality/LiqualitySwapProvider.js
Labels: 🔍 Ready for Review, size/M
