Repository liquality/wallet, pull requests merged in 2022-08, with the labels that each got.

#848 feat: update wallet core version and rounding fix
  package.json
  src/views/Swap/Swap.vue
  yarn.lock
Labels: size/L, ✅ Approved

#684 feat: NFTs integration
  src/assets/icons/angle_down.svg
  src/assets/icons/angle_right.svg
  src/assets/icons/nft.svg
  src/assets/icons/opensea.svg
  src/assets/icons/send_nft.svg
  src/assets/icons/share_nft.svg
  src/assets/nft_preview.png
  src/assets/nft_thumbnail.png
  src/assets/scss/_overrides.scss
  src/assets/scss/style.scss
  src/background.js
  src/components/Accordion.vue
  src/components/CustomFeesEIP1559.vue
  src/components/NFTAsset.vue
  src/components/NFTAssets.vue
  src/components/NavBar.vue
  src/components/Star.vue
  src/components/TransactionList.vue
  src/components/WalletAccounts.vue
  src/router/index.js
  src/transactions/views/NFTTimeline.vue
  src/views/Account.vue
  src/views/AssetList.vue
  src/views/Details/NFTAssetDetails.vue
  src/views/Details/NFTCollectionList.vue
  src/views/Details/NFTTransactionDetails.vue
  src/views/Send/SendNFT.vue
  src/views/Wallet/NFTActivity.vue
  src/views/Wallet/NFTStats.vue
  src/views/Wallet/Wallet.vue
  src/views/Wallet/WalletNFTs.vue
  src/views/Wallet/WalletTabs.vue
Labels: size/XXL, 🔍 Ready for Review

#849 chore: rc 0.69.0 into master
  package.json
  src/components/WhatsNewModal.vue
  src/manifest.json
  src/views/Account.vue
  src/views/AssetList.vue
  src/views/Swap/Accounts.vue
  src/views/Swap/Swap.vue
  yarn.lock
Labels: size/L, 🔍 Ready for Review

#852 chore: rc 0.70.0 merge into master
  package.json
  src/assets/icons/angle_down.svg
  src/assets/icons/angle_right.svg
  src/assets/icons/nft.svg
  src/assets/icons/opensea.svg
  src/assets/icons/send_nft.svg
  src/assets/icons/share_nft.svg
  src/assets/nft_preview.png
  src/assets/nft_thumbnail.png
  src/assets/scss/_overrides.scss
  src/assets/scss/style.scss
  src/background.js
  src/components/Accordion.vue
  src/components/CustomFeesEIP1559.vue
  src/components/NFTAsset.vue
  src/components/NFTAssets.vue
  src/components/NavBar.vue
  src/components/Star.vue
  src/components/TransactionList.vue
  src/components/WalletAccounts.vue
  src/components/WhatsNewModal.vue
  src/manifest.json
  src/router/index.js
  src/transactions/views/NFTTimeline.vue
  src/views/Account.vue
  src/views/AssetList.vue
  src/views/Details/NFTAssetDetails.vue
  src/views/Details/NFTCollectionList.vue
  src/views/Details/NFTTransactionDetails.vue
  src/views/Send/SendNFT.vue
  src/views/Wallet/NFTActivity.vue
  src/views/Wallet/NFTStats.vue
  src/views/Wallet/Wallet.vue
  src/views/Wallet/WalletNFTs.vue
  src/views/Wallet/WalletTabs.vue
  test/e2e/add_custom_token.spec.js
  test/e2e/dapp_injection_tests/sushi_dapp_injection.spec.js
  test/e2e/enable_disable_assets.spec.js
  test/e2e/hop_tests/hop_swaps.spec.js
  test/e2e/service_provider_tests/oneinch_swap_provider.spec.js
  test/pages/OverviewPage.js
  test/pages/PasswordPage.js
  test/pages/SwapPage.js
  yarn.lock
Labels: size/XXL, 🔍 Ready for Review

#851 fix: refactor fetching token details
  package.json
  src/views/CustomToken.vue
  src/views/PermissionSend.vue
  yarn.lock
Labels: size/L, ✅ Approved

#855 feat: fast btc rbtc -> btc
  package.json
  src/views/Swap/SwapInfo.vue
  yarn.lock
Labels: size/S, 🔍 Ready for Review

#856 [LIQ-213] NFT fixes
  package.json
  src/assets/icons/stratosnft.svg
  src/background.js
  src/components/ActivityFilter.vue
  src/components/NFT/NFTAsset.vue
  src/components/NFT/NFTAssets.vue
  src/components/NFT/NFTQuantity.vue
  src/components/NFT/NFTTimeline.vue
  src/components/NFT/Star.vue
  src/views/Account.vue
  src/views/Details/NFTAssetDetails.vue
  src/views/Details/NFTCollectionList.vue
  src/views/Details/NFTTransactionDetails.vue
  src/views/Send/SendNFT.vue
  src/views/Swap/SwapInfo.vue
  src/views/Wallet/NFTActivity.vue
  src/views/Wallet/NFTStats.vue
  src/views/Wallet/Wallet.vue
  src/views/Wallet/WalletActivity.vue
  src/views/Wallet/WalletNFTs.vue
  yarn.lock
Labels: size/XL, 🔍 Ready for Review
