Repository liquality/wallet, pull requests merged in 2023-01, with the labels that each got.

#972 feat: enabled by default manage accounts
  package.json
  src/components/NavBar.vue
  src/manifest.json
  src/views/Experiments.vue
  yarn.lock
Labels: ✅ Approved, size/M

#973 Fix/pre release fixes
  package.json
  src/App.vue
  src/broker/index.js
  src/locales/cb/pages.json
  src/locales/en/pages.json
  src/locales/es/pages.json
  src/locales/ph/pages.json
  src/locales/pt/pages.json
  src/locales/zh/pages.json
  src/manifest.json
  src/swaps/views/Timeline.vue
  src/views/Details/SwapDetails.vue
Labels: 🔍 Ready for Review, size/M

#976 EXT-223 | Account Activity filter fixes and Polygon error fix
  src/swaps/views/Timeline.vue
  src/views/Account.vue
  src/views/Send/SendNFT.vue
  src/views/Wallet/NFTActivity.vue
Labels: size/S, ✅ Approved

#978 fix: some fixes for nft screens
  package.json
  src/manifest.json
  src/views/Send/SendNFT.vue
  src/views/Wallet/NFTActivity.vue
  yarn.lock
Labels: ✅ Approved, size/M

#979 Publishing version 0.83.0
  .env
  package.json
  src/locales/cb/pages.json
  src/locales/cb/whats_new.json
  src/locales/en/pages.json
  src/locales/en/whats_new.json
  src/locales/es/pages.json
  src/locales/es/whats_new.json
  src/locales/ph/pages.json
  src/locales/ph/whats_new.json
  src/locales/pt/pages.json
  src/locales/pt/whats_new.json
  src/locales/zh/pages.json
  src/locales/zh/whats_new.json
  src/main.js
  src/manifest.json
  src/router/index.js
  src/swaps/views/Timeline.vue
  src/views/Account.vue
  src/views/Details/SwapDetails.vue
  src/views/PermissionSend.vue
  src/views/Send/SendNFT.vue
  src/views/Swap/Accounts.vue
  src/views/Swap/Swap.vue
  src/views/UnlockWallet.vue
  src/views/Wallet/NFTActivity.vue
  yarn.lock
Labels: size/XL, 🔍 Ready for Review

#980 Ext 253/gas fee handler
  package.json
  src/manifest.json
  src/views/Send/Send.vue
  src/views/Send/SendNFT.vue
Labels: ✅ Approved, size/M

#982 Ext 256/custom rpc settins form fix
  src/components/CustomRpcSettingsForm.vue
  src/components/NavBar.vue
  src/locales/cb/pages.json
  src/locales/en/pages.json
  src/locales/es/pages.json
  src/locales/ph/pages.json
  src/locales/pt/pages.json
  src/locales/zh/pages.json
  src/views/Accounts/Manage.vue
  src/views/SettingItems.vue
Labels: ✅ Approved, size/M

#981 EXT-253 | Receive Screen error fix
  src/views/Receive.vue
  src/views/Send/Send.vue
Labels: size/XS, ✅ Approved

#983 EXT-257 | Copy address tooltip inside Asset fix
  src/views/Account.vue
Labels: size/S, ✅ Approved

#986 Password error message fix
  src/views/UnlockWallet.vue
Labels: size/XS, 🔍 Ready for Review

#987 fix: fixed permission sign screen for eip 712 and v1
  package.json
  src/components/Modal.vue
  src/locales/cb/common.json
  src/locales/cb/pages.json
  src/locales/en/common.json
  src/locales/en/pages.json
  src/locales/es/common.json
  src/locales/es/pages.json
  src/locales/ph/common.json
  src/locales/ph/pages.json
  src/locales/pt/common.json
  src/locales/pt/pages.json
  src/locales/zh/common.json
  src/locales/zh/pages.json
  src/manifest.json
  src/views/PermissionSign.vue
Labels: size/L, 🔍 Ready for Review

#988 fix: fixes for EIP-712 injection
  package.json
  src/locales/cb/pages.json
  src/locales/cb/whats_new.json
  src/locales/en/pages.json
  src/locales/en/whats_new.json
  src/locales/es/pages.json
  src/locales/es/whats_new.json
  src/locales/ph/pages.json
  src/locales/ph/whats_new.json
  src/locales/pt/pages.json
  src/locales/pt/whats_new.json
  src/locales/zh/pages.json
  src/locales/zh/whats_new.json
  src/manifest.json
  src/views/PermissionSign.vue
Labels: 🔍 Ready for Review, size/M
